// vendored from @patternmode/system@0.4.0 — generated by scripts/build-registry.mjs; do not hand-edit.
export {
  type DerivedDistribution,
  deriveDistribution,
  isLightColor,
  sanitizeWeight,
} from "./weighted-distribution";

export const PATTERNMODE_SIZES = ["2xs", "xs", "sm", "base", "lg", "xl", "2xl", "3xl"] as const;

/** Shared size token names used by Patternmode primitives. */
export type PatternmodeSize = (typeof PATTERNMODE_SIZES)[number];

/** CSS size value accepted by helpers; numbers are interpreted as pixels. */
export type CssSize = number | string;

export const PATTERNMODE_SIZE_VALUES = {
  "2xl": "3.5rem",
  "2xs": "1rem",
  "3xl": "4rem",
  base: "2rem",
  lg: "2.5rem",
  sm: "1.5rem",
  xl: "3rem",
  xs: "1.25rem",
} as const satisfies Record<PatternmodeSize, string>;

export const PATTERNMODE_SIZE_PIXELS = {
  "2xl": 56,
  "2xs": 16,
  "3xl": 64,
  base: 32,
  lg: 40,
  sm: 24,
  xl: 48,
  xs: 20,
} as const satisfies Record<PatternmodeSize, number>;

export const getPatternmodeSizeValue = (size: PatternmodeSize): string =>
  PATTERNMODE_SIZE_VALUES[size];

/** Converts numeric size values to pixel strings while preserving CSS strings. */
export const toCssSize = (value: CssSize | undefined): string | undefined => {
  if (typeof value === "number") {
    return `${value}px`;
  }
  return value;
};

/** Builds a CSS custom-property style object for a Patternmode size token. */
export const getSizeVariableStyle = (
  size: PatternmodeSize,
  variableName = "--patternmode-size",
): Record<string, string> => ({
  [variableName]: getPatternmodeSizeValue(size),
});

export type ClassNameValue = false | null | string | undefined;

/** Joins class names and returns `undefined` when no truthy classes remain. */
export const joinClassNames = (...parts: ClassNameValue[]): string | undefined => {
  const out = parts.filter(Boolean).join(" ").trim();
  return out.length > 0 ? out : undefined;
};

export const OBJECT_FITS = ["contain", "cover", "fill", "none", "scale-down"] as const;

export type ObjectFit = (typeof OBJECT_FITS)[number];

/** Object sizing options shared by media-like primitives. */
export interface ObjectSizing {
  /**
   * CSS `object-fit` value.
   *
   * Default `"cover"`.
   */
  fit?: ObjectFit;
  /**
   * CSS height; numbers are interpreted as pixels.
   *
   * Default `"100%"`.
   */
  height?: CssSize;
  /**
   * CSS `object-position` value.
   *
   * Default `"center"`.
   */
  position?: string;
  /**
   * CSS width; numbers are interpreted as pixels.
   *
   * Default `"100%"`.
   */
  width?: CssSize;
}

/** Normalized object sizing style with concrete CSS strings. */
export interface ObjectSizingStyle {
  height: string;
  objectFit: ObjectFit;
  objectPosition: string;
  width: string;
}

/** Resolves object sizing props into a complete inline style object. */
export const getObjectSizingStyle = (sizing: ObjectSizing = {}): ObjectSizingStyle => ({
  height: toCssSize(sizing.height) ?? "100%",
  objectFit: sizing.fit ?? "cover",
  objectPosition: sizing.position ?? "center",
  width: toCssSize(sizing.width) ?? "100%",
});

/**
 * One weighted color in a distribution — the shared input shape behind both
 * Swatch's Distribution Segments and Parquet's Tiles. The same array can drive a
 * one-dimensional `DistributionBar` and a two-dimensional `Parquet`.
 */
export interface WeightedColorSegment {
  /** Any CSS color string. */
  color: string;
  /** Relative weight, not a persisted percentage. Invalid or negative values are treated as 0. */
  value: number;
  /** Optional human-readable label for the color. */
  label?: string;
}
