// vendored from @patternmode/system@0.4.0 — generated by scripts/build-registry.mjs; do not hand-edit.
import { hexLightness, hslToRgb, rgbToOklab } from "@instruments/colorscope/math";

/**
 * Shared logic for rendering weighted color segments — the one place that owns
 * how a raw distribution value is sanitized, totalled, and turned into a
 * percentage, plus the single contrast decision for whether a color reads as
 * light. Both Swatch's Distribution Bar and Parquet's Tiles derive through here
 * instead of re-implementing the math, so the same input reads the same way in
 * one and two dimensions.
 */

/**
 * Treats a single distribution weight as a non-negative number: non-finite or
 * negative values become `0`. A `0` stays `0` — dropping zero-weight entries is
 * the caller's policy (Parquet filters them out; Distribution Bar keeps them as
 * identity-bearing zero-width segments).
 */
export const sanitizeWeight = (value: number): number =>
  Number.isFinite(value) && value > 0 ? value : 0;

/** The sanitized weights, their total, and each weight's share of the total. */
export interface DerivedDistribution {
  /** Input values with non-finite or negative entries coerced to `0`. */
  sanitized: number[];
  /** Sum of the sanitized weights. */
  total: number;
  /**
   * Each sanitized weight as an unrounded percentage (0–100) of the total.
   * When the total is `0`, every percentage is `0` — any equal-weight fallback
   * for an all-zero distribution is the caller's policy.
   */
  percentages: number[];
}

/**
 * Derives the sanitized weights, total, and unrounded percentages for one
 * weighted distribution. Pure: callers round percentages for display and decide
 * whether to drop or keep zero-weight entries.
 */
export const deriveDistribution = (values: number[]): DerivedDistribution => {
  const sanitized = values.map(sanitizeWeight);
  const total = sanitized.reduce((sum, weight) => sum + weight, 0);
  const percentages = sanitized.map((weight) => (total > 0 ? (weight / total) * 100 : 0));

  return { percentages, sanitized, total };
};

/** Perceptual (OKLab) lightness above which a color reads as "light". */
const LIGHT_LIGHTNESS_THRESHOLD = 0.62;

const NAMED_COLOR_LIGHTNESS: Record<string, boolean> = {
  black: false,
  transparent: false,
  white: true,
};

/**
 * Splits a CSS color function body into channel tokens, accepting both the
 * legacy comma syntax and the modern space syntax. Alpha (after `/` or as a
 * fourth comma argument) is ignored — tone only depends on the channels.
 */
const getColorFunctionChannels = (color: string, names: readonly string[]): string[] | null => {
  const match = /^(?<name>[a-z]+)\(\s*(?<body>[^)]+?)\s*\)$/iu.exec(color.trim());
  if (match === null) {
    return null;
  }

  const { body = "", name = "" } = match.groups ?? {};
  if (!names.includes(name.toLowerCase())) {
    return null;
  }

  const channels = (body.split("/")[0] ?? "").split(/[\s,]+/u).filter(Boolean);
  return channels.length >= 3 ? channels.slice(0, 3) : null;
};

/** Parses a channel token against its full-scale value; percentages map to it. */
const parseChannel = (token: string, scale: number): number | null => {
  const value = Number.parseFloat(token);
  if (!Number.isFinite(value)) {
    return null;
  }

  return token.endsWith("%") ? (value / 100) * scale : value;
};

const getRgbFunctionLightness = (color: string): number | null => {
  const channels = getColorFunctionChannels(color, ["rgb", "rgba"]);
  if (channels === null) {
    return null;
  }

  const [red, green, blue] = channels.map((token) => parseChannel(token, 255));
  if (red === null || green === null || blue === null) {
    return null;
  }

  return rgbToOklab(red ?? 0, green ?? 0, blue ?? 0).L;
};

const getHslFunctionLightness = (color: string): number | null => {
  const channels = getColorFunctionChannels(color, ["hsl", "hsla"]);
  if (channels === null) {
    return null;
  }

  const hue = Number.parseFloat(channels[0] ?? "");
  const saturation = parseChannel(channels[1] ?? "", 100);
  const lightness = parseChannel(channels[2] ?? "", 100);
  if (!Number.isFinite(hue) || saturation === null || lightness === null) {
    return null;
  }

  const rgb = hslToRgb(hue, saturation, lightness);
  return rgbToOklab(rgb.r, rgb.g, rgb.b).L;
};

/** `oklab()`/`oklch()` lead with the perceptual L channel; use it directly. */
const getOkFunctionLightness = (color: string): number | null => {
  const channels = getColorFunctionChannels(color, ["oklab", "oklch"]);
  if (channels === null) {
    return null;
  }

  return parseChannel(channels[0] ?? "", 1);
};

/**
 * Whether a color reads as light, by perceptual (OKLab) lightness above a
 * single shared threshold — so contrast treatment (e.g. dark foreground over a
 * light fill) is decided the same way wherever a weighted color is rendered.
 * Parses hex, `rgb()`/`rgba()`, `hsl()`/`hsla()`, `oklab()`/`oklch()`, and the
 * named colors `white`/`black`/`transparent`; returns `false` for anything it
 * cannot parse.
 */
export const isLightColor = (color: string): boolean => {
  const named = NAMED_COLOR_LIGHTNESS[color.trim().toLowerCase()];
  if (named !== undefined) {
    return named;
  }

  // Function syntaxes first: hexLightness coerces anything non-hex to 0.
  const lightness =
    getRgbFunctionLightness(color) ??
    getHslFunctionLightness(color) ??
    getOkFunctionLightness(color) ??
    hexLightness(color);
  return Number.isFinite(lightness) && lightness > LIGHT_LIGHTNESS_THRESHOLD;
};
