"use client";
// vendored from @patternmode/scrollframe@2.0.2 — generated by scripts/build-registry.mjs; do not hand-edit.

import { joinClassNames } from "@/lib/patternmode/system";
import { ChevronLeft, ChevronRight } from "lucide-react";
import type { MouseEvent } from "react";

import { useRender } from "../render";
import { useScrollFrame } from "./scroll-frame-context";
import type {
  ScrollFrameEdge,
  ScrollFrameEdgeState,
  ScrollFrameMovementControlProps,
} from "./scroll-frame-types";
import { defaultControlAxis } from "./scroll-frame-utils";

const isMovementBlocked = (
  axisState: ScrollFrameEdgeState[keyof ScrollFrameEdgeState],
  direction: ScrollFrameEdge,
) => !axisState.scrollable || (direction === "start" ? axisState.atStart : axisState.atEnd);

const getControlLabel = (label: string | undefined, direction: ScrollFrameEdge) =>
  label ?? (direction === "start" ? "Scroll backward" : "Scroll forward");

const getControlIcon = (direction: ScrollFrameEdge) =>
  direction === "start" ? (
    <ChevronLeft aria-hidden="true" size={16} strokeWidth={2} />
  ) : (
    <ChevronRight aria-hidden="true" size={16} strokeWidth={2} />
  );

const ScrollFrameMovementControl = ({
  render,
  axis,
  children,
  className,
  direction,
  disabled,
  onClick,
  type,
  visibility,
  ...props
}: ScrollFrameMovementControlProps & { direction: ScrollFrameEdge }) => {
  const { axes, controlVisibility, edgeState, scrollByStep } = useScrollFrame();
  const isRendered = render !== undefined;
  const resolvedAxis = axis ?? defaultControlAxis(axes);
  const resolvedVisibility = visibility ?? controlVisibility;
  const axisState = edgeState[resolvedAxis];
  const movementBlocked = isMovementBlocked(axisState, direction);
  const hidden =
    resolvedVisibility === "hidden" || (resolvedVisibility === "auto" && movementBlocked);
  const controlDisabled = disabled === true || movementBlocked;
  const label = getControlLabel(props["aria-label"], direction);

  // `useRender` must run unconditionally, so build the element before the
  // early return and gate rendering on `hidden` afterwards.
  const element = useRender({
    defaultTagName: "button",
    props: {
      ...props,
      "aria-disabled": isRendered && controlDisabled ? true : props["aria-disabled"],
      "aria-label": label,
      children: children ?? getControlIcon(direction),
      className: joinClassNames("patternmode-scrollframe__control", className),
      "data-axis": resolvedAxis,
      "data-direction": direction,
      "data-slot": "scrollframe-control",
      disabled: isRendered ? undefined : controlDisabled,
      onClick: (event: MouseEvent<HTMLButtonElement>) => {
        onClick?.(event);
        if (!event.defaultPrevented && !controlDisabled) {
          scrollByStep(direction, resolvedAxis);
        }
      },
      type: isRendered ? undefined : (type ?? "button"),
    },
    render,
  });

  if (hidden) {
    return null;
  }

  return element;
};

export const ScrollFramePrevious = (props: ScrollFrameMovementControlProps) => (
  <ScrollFrameMovementControl {...props} direction="start" />
);

export const ScrollFrameNext = (props: ScrollFrameMovementControlProps) => (
  <ScrollFrameMovementControl {...props} direction="end" />
);
