"use client";
// vendored from @patternmode/scrollframe@2.0.2 — generated by scripts/build-registry.mjs; do not hand-edit.

import { ScrollArea } from "@base-ui/react/scroll-area";
import { joinClassNames } from "@/lib/patternmode/system";
import type { MouseEvent, PointerEvent } from "react";
import { useEffect, useRef } from "react";

import { useScrollFrame } from "./scroll-frame-context";
import type {
  ScrollFrameContextValue,
  ScrollFrameResolvedDragScrollConfig,
  ScrollFrameViewportProps,
} from "./scroll-frame-types";
import { getMaskVars, isDragScrollIgnored, setRef, supportsAxis } from "./scroll-frame-utils";

const getDragDistance = (
  offset: { x: number; y: number },
  axis: "horizontal" | "vertical" | "both",
): number => {
  if (axis === "horizontal") {
    return Math.abs(offset.x);
  }
  if (axis === "vertical") {
    return Math.abs(offset.y);
  }
  return Math.hypot(offset.x, offset.y);
};

const resolveDragAxis = (
  offset: { x: number; y: number },
  contextAxes: "vertical" | "horizontal" | "both",
  configAxis: "auto" | "vertical" | "horizontal" | "both",
) => {
  if (configAxis !== "auto") {
    return configAxis;
  }
  if (contextAxes !== "both") {
    return contextAxes;
  }
  return Math.abs(offset.x) >= Math.abs(offset.y) ? "horizontal" : "vertical";
};

interface DragScrollSession {
  pointerId: number;
  scrollLeft: number;
  scrollTop: number;
  startX: number;
  startY: number;
}

const clearPageSelection = () => {
  if (typeof window === "undefined") {
    return;
  }
  window.getSelection()?.removeAllRanges();
};

const canStartDrag = (
  event: PointerEvent<HTMLDivElement>,
  dragScroll: ScrollFrameResolvedDragScrollConfig,
) => event.button === 0 && !isDragScrollIgnored(event.target, dragScroll.ignoreSelector);

const useDragScrollHandlers = ({
  axes,
  dragScroll,
  setDragging,
  viewport,
}: Pick<ScrollFrameContextValue, "axes" | "dragScroll" | "setDragging" | "viewport">) => {
  const sessionRef = useRef<DragScrollSession | null>(null);
  const committedRef = useRef(false);
  const suppressClickRef = useRef(false);
  const detachRef = useRef<(() => void) | null>(null);
  // The move handler is recreated every render and closes over `axes`,
  // `dragScroll` and `viewport`; the window listener must always call the
  // current one rather than the one captured when the gesture began.
  const trackRef = useRef<(event: globalThis.PointerEvent) => void>(() => {
    // Replaced on every render; only a no-op before the first one.
  });
  const endRef = useRef<() => void>(() => {
    // As above.
  });

  const detachWindowTracking = () => {
    detachRef.current?.();
    detachRef.current = null;
  };

  const attachWindowTracking = () => {
    detachWindowTracking();
    if (typeof window === "undefined") {
      return;
    }
    const onMove = (event: globalThis.PointerEvent) => {
      trackRef.current(event);
    };
    const onEnd = () => {
      endRef.current();
    };
    window.addEventListener("pointermove", onMove, { capture: true });
    window.addEventListener("pointerup", onEnd, { capture: true });
    window.addEventListener("pointercancel", onEnd, { capture: true });
    detachRef.current = () => {
      window.removeEventListener("pointermove", onMove, { capture: true });
      window.removeEventListener("pointerup", onEnd, { capture: true });
      window.removeEventListener("pointercancel", onEnd, { capture: true });
    };
  };

  const endDrag = () => {
    detachWindowTracking();
    if (committedRef.current) {
      setDragging(false);
      // The click that follows a drag has not been dispatched yet, so the
      // suppression flag has to outlive this call — but only just. Clearing it
      // on a macrotask lets the trailing click (dispatched synchronously after
      // pointerup) still be swallowed, while making sure a gesture that never
      // produces a click cannot leave the flag set and eat somebody else's
      // click minutes later.
      setTimeout(() => {
        suppressClickRef.current = false;
      }, 0);
    }
    sessionRef.current = null;
    committedRef.current = false;
  };

  const handlePointerDownCapture = (event: PointerEvent<HTMLDivElement>) => {
    const activeDragScroll = dragScroll;
    const activeViewport = viewport;
    if (
      activeDragScroll === null ||
      activeViewport === null ||
      !canStartDrag(event, activeDragScroll)
    ) {
      sessionRef.current = null;
      return;
    }

    sessionRef.current = {
      pointerId: event.pointerId,
      scrollLeft: activeViewport.scrollLeft,
      scrollTop: activeViewport.scrollTop,
      startX: event.clientX,
      startY: event.clientY,
    };
    committedRef.current = false;
    // Pointer capture is deliberately never taken.
    //
    // Capturing retargets the whole gesture — including the compatibility
    // `mouseup` and `click` — at the capturing element. A click delivered to
    // the scroll container instead of the element under the cursor never
    // activates that element, so every link and button inside a
    // drag-scrollable frame silently stops working: press an anchor, release,
    // nothing happens, nothing thrown, nothing prevented.
    //
    // Capture was there to keep the gesture alive when the cursor leaves the
    // frame. Window-level listeners do that without touching event targeting,
    // and they also cover the case capture never did: a drag that begins
    // within the activation distance of the edge and pulls straight out, where
    // the deciding move lands outside the element and the drag never starts.
    attachWindowTracking();
  };

  /**
   * Runs for every move in the gesture, whether the cursor is still inside the
   * frame or not. Takes the DOM event rather than React's synthetic one so the
   * window listener and the element handler can share it.
   */
  const trackDrag = (event: globalThis.PointerEvent | PointerEvent<HTMLDivElement>) => {
    const session = sessionRef.current;
    if (
      !(
        dragScroll !== null &&
        viewport !== null &&
        session !== null &&
        event.pointerId === session.pointerId
      )
    ) {
      return;
    }

    const offset = {
      x: event.clientX - session.startX,
      y: event.clientY - session.startY,
    };
    const axis = resolveDragAxis(offset, axes, dragScroll.axis);
    const canScrollHorizontally =
      (axis === "horizontal" || axis === "both") && supportsAxis(axes, "horizontal");
    const canScrollVertically =
      (axis === "vertical" || axis === "both") && supportsAxis(axes, "vertical");
    if (!(canScrollHorizontally || canScrollVertically)) {
      return;
    }

    if (!committedRef.current) {
      if (getDragDistance(offset, axis) < dragScroll.activationDistance) {
        return;
      }
      committedRef.current = true;
      suppressClickRef.current = true;
      setDragging(true);
    }

    clearPageSelection();
    if (canScrollHorizontally) {
      viewport.scrollLeft = session.scrollLeft - offset.x;
    }
    if (canScrollVertically) {
      viewport.scrollTop = session.scrollTop - offset.y;
    }
    event.preventDefault();
  };

  const handlePointerEndCapture = () => {
    endDrag();
  };

  const handleClickCapture = (event: MouseEvent<HTMLDivElement>) => {
    if (!suppressClickRef.current) {
      return;
    }
    // Left set until the macrotask scheduled in `endDrag`, so a gesture that
    // ends without producing a click cannot strand it.
    event.preventDefault();
    event.stopPropagation();
  };

  // Window listeners call through refs so they always run the current closure,
  // and so a component unmounting mid-gesture cannot leave them attached.
  trackRef.current = trackDrag;
  endRef.current = endDrag;
  useEffect(
    () => () => {
      detachWindowTracking();
    },
    [],
  );

  return {
    handleClickCapture,
    handlePointerDownCapture,
    handlePointerEndCapture,
    handlePointerMoveCapture: trackDrag,
  };
};

export const ScrollFrameViewport = ({
  children,
  className,
  contentClassName,
  contentStyle,
  ref,
  style,
  viewportRef,
  ...props
}: ScrollFrameViewportProps) => {
  const context = useScrollFrame();
  const { axes, dragScroll, edgeState, fadeMode, fades, registerViewport, setDragging, viewport } =
    context;
  const {
    handleClickCapture,
    handlePointerDownCapture,
    handlePointerEndCapture,
    handlePointerMoveCapture,
  } = useDragScrollHandlers({ axes, dragScroll, setDragging, viewport });
  const assignRef = (node: HTMLDivElement | null) => {
    registerViewport(node);
    setRef(ref, node);
    setRef(viewportRef, node);
  };
  const maskStyle = fadeMode === "mask" ? getMaskVars(axes, edgeState, fades) : undefined;

  return (
    <ScrollArea.Viewport
      {...props}
      className={joinClassNames("patternmode-scrollframe__viewport", className)}
      data-fade-mode={fadeMode === "mask" ? "mask" : undefined}
      data-slot="scrollframe-viewport"
      ref={assignRef}
      style={maskStyle === undefined ? style : { ...maskStyle, ...style }}
    >
      <div
        className={joinClassNames("patternmode-scrollframe__content", contentClassName)}
        data-scrollframe-drag-surface={dragScroll === null ? undefined : ""}
        data-slot="scrollframe-content"
        onClickCapture={handleClickCapture}
        onPointerCancelCapture={handlePointerEndCapture}
        onPointerDownCapture={handlePointerDownCapture}
        onPointerMoveCapture={handlePointerMoveCapture}
        onPointerUpCapture={handlePointerEndCapture}
        style={contentStyle}
      >
        {children}
      </div>
    </ScrollArea.Viewport>
  );
};
