"use client";
// vendored from @patternmode/scrollframe@1.0.0 — generated by scripts/build-registry.mjs; do not hand-edit.

import { ScrollFrameNext, ScrollFramePrevious } from "./scroll-frame-controls";
import { ScrollFrameFade } from "./scroll-frame-fade";
import { ScrollFrameRoot } from "./scroll-frame-root";
import {
  ScrollFrameCorner,
  ScrollFrameScrollbar,
  ScrollFrameThumb,
} from "./scroll-frame-scrollbar";
import type { ScrollFrameAxis, ScrollFrameProps } from "./scroll-frame-types";
import { defaultControlAxis, shouldRenderFade, supportsAxis } from "./scroll-frame-utils";
import { ScrollFrameViewport } from "./scroll-frame-viewport";

const SCROLL_FRAME_FADE_EDGES = ["start", "end"] as const;

const getFadeAxes = (axes: ScrollFrameProps["axes"]): ScrollFrameAxis[] => {
  if (axes === "both") {
    return ["vertical", "horizontal"];
  }
  return [axes ?? "vertical"];
};

const ScrollFrameFades = ({ axes, fades }: Pick<ScrollFrameProps, "axes" | "fades">) =>
  getFadeAxes(axes).map((axis) =>
    SCROLL_FRAME_FADE_EDGES.map((edge) =>
      shouldRenderFade(fades, axis, edge) ? (
        <ScrollFrameFade axis={axis} edge={edge} key={`${axis}-${edge}`} />
      ) : null,
    ),
  );

const ScrollFrameScrollbars = ({ axes }: Pick<ScrollFrameProps, "axes">) => (
  <>
    {supportsAxis(axes ?? "vertical", "vertical") ? (
      <ScrollFrameScrollbar orientation="vertical">
        <ScrollFrameThumb />
      </ScrollFrameScrollbar>
    ) : null}
    {supportsAxis(axes ?? "vertical", "horizontal") ? (
      <ScrollFrameScrollbar orientation="horizontal">
        <ScrollFrameThumb />
      </ScrollFrameScrollbar>
    ) : null}
    {axes === "both" ? <ScrollFrameCorner /> : null}
  </>
);

const ScrollFrameBase = ({
  axes = "vertical",
  children,
  contentClassName,
  contentStyle,
  controls = false,
  controlVisibility,
  dragScroll,
  fadeMode = "color",
  fades = true,
  ref,
  scrollbars = "auto",
  viewportClassName,
  viewportRef,
  viewportStyle,
  ...props
}: ScrollFrameProps) => {
  const controlConfig = typeof controls === "object" ? controls : {};
  const controlsEnabled = controls !== false;
  const controlAxis = controlConfig.axis ?? defaultControlAxis(axes);
  const visibility =
    controlConfig.visibility ?? controlVisibility ?? (controlsEnabled ? "auto" : "hidden");

  return (
    <ScrollFrameRoot
      {...props}
      axes={axes}
      controlVisibility={visibility}
      dragScroll={dragScroll}
      fadeMode={fadeMode}
      fades={fades}
      ref={ref}
      scrollbars={scrollbars}
    >
      {controlsEnabled ? <ScrollFramePrevious axis={controlAxis} visibility={visibility} /> : null}
      <ScrollFrameViewport
        className={viewportClassName}
        contentClassName={contentClassName}
        contentStyle={contentStyle}
        style={viewportStyle}
        viewportRef={viewportRef}
      >
        {children}
      </ScrollFrameViewport>
      {fadeMode === "mask" ? null : <ScrollFrameFades axes={axes} fades={fades} />}
      <ScrollFrameScrollbars axes={axes} />
      {controlsEnabled ? <ScrollFrameNext axis={controlAxis} visibility={visibility} /> : null}
    </ScrollFrameRoot>
  );
};

const ScrollFrame = Object.assign(ScrollFrameBase, {
  Corner: ScrollFrameCorner,
  Fade: ScrollFrameFade,
  Next: ScrollFrameNext,
  Previous: ScrollFramePrevious,
  Root: ScrollFrameRoot,
  Scrollbar: ScrollFrameScrollbar,
  Thumb: ScrollFrameThumb,
  Viewport: ScrollFrameViewport,
});

export { ScrollFrame };
