// vendored from @patternmode/scrollframe@1.0.0 — generated by scripts/build-registry.mjs; do not hand-edit.
import { createContext, use } from "react";

import type {
  ScrollFrameAxisState,
  ScrollFrameContextValue,
  ScrollFrameEdgeState,
} from "./scroll-frame-types";

const DEFAULT_AXIS_STATE: ScrollFrameAxisState = {
  atEnd: true,
  atStart: true,
  scrollable: false,
};

export const DEFAULT_EDGE_STATE: ScrollFrameEdgeState = {
  horizontal: DEFAULT_AXIS_STATE,
  vertical: DEFAULT_AXIS_STATE,
};

export const ScrollFrameContext = createContext<ScrollFrameContextValue | null>(null);

/**
 * Reads the nearest ScrollFrame root state for compound controls.
 *
 * Must be called under `ScrollFrame.Root`; it throws when used outside the
 * provider so custom parts fail fast during development.
 */
export const useScrollFrame = (): ScrollFrameContextValue => {
  const context = use(ScrollFrameContext);
  if (!context) {
    throw new Error("useScrollFrame must be used within <ScrollFrame.Root>.");
  }
  return context;
};
