// vendored from @patternmode/stacksheet@2.0.3 — generated by scripts/build-registry.mjs; do not hand-edit.
import { ArrowLeftIcon, XIcon } from "../icons";
import type { HeaderRenderProps } from "../types";

// No header bar: back and close float in the panel corners so there is no
// row to fill and no divider. The title lives in the sheet's own content.
export const DefaultHeader = ({ isNested, onBack, onClose }: HeaderRenderProps) => (
  <>
    {isNested && (
      <button
        aria-label="Back"
        className="absolute left-2 top-2 z-20 flex min-h-11 min-w-11 cursor-pointer items-center justify-center rounded-md border-none bg-transparent p-0 text-inherit opacity-50 transition-opacity duration-150 hover:opacity-100"
        onClick={onBack}
        type="button"
      >
        <ArrowLeftIcon />
      </button>
    )}
    <button
      aria-label="Close"
      className="absolute right-2 top-2 z-20 flex min-h-11 min-w-11 cursor-pointer items-center justify-center rounded-md border-none bg-transparent p-0 text-inherit opacity-50 transition-opacity duration-150 hover:opacity-100"
      onClick={onClose}
      type="button"
    >
      <XIcon />
    </button>
  </>
);
