// vendored from @patternmode/stacksheet@2.0.0 — generated by scripts/build-registry.mjs; do not hand-edit.
import type { ComponentType, ReactNode } from "react";

import type { HeaderRenderProps } from "../types";
import { DefaultHeader } from "./default-header";

export const PanelInnerContent = ({
  isComposable,
  shouldRender,
  Content,
  data,
  renderHeader,
  headerProps,
}: {
  isComposable: boolean;
  shouldRender: boolean;
  Content: ComponentType<Record<string, unknown>> | undefined;
  data: Record<string, unknown>;
  renderHeader?: false | ((props: HeaderRenderProps) => ReactNode);
  headerProps: HeaderRenderProps;
}) => {
  if (isComposable) {
    return shouldRender && Content !== undefined ? <Content {...data} /> : null;
  }
  const customHeader =
    renderHeader !== undefined && renderHeader !== false ? renderHeader : undefined;

  return (
    <>
      {customHeader === undefined ? <DefaultHeader {...headerProps} /> : customHeader(headerProps)}
      {shouldRender && Content !== undefined && (
        <div
          className="min-h-0 flex-1 overflow-y-auto overscroll-contain"
          data-stacksheet-no-drag=""
        >
          <Content {...data} />
        </div>
      )}
    </>
  );
};

PanelInnerContent.displayName = "PanelInnerContent";
