// vendored from @patternmode/stacksheet@2.0.3 — generated by scripts/build-registry.mjs; do not hand-edit.
import type { ComponentType, ReactNode } from "react";

import type { ResolvedClassNames } from "../renderer-helpers";
import type { SlideValues } from "../stacking";
import type {
  HeaderRenderProps,
  ResolvedConfig,
  SheetItem,
  Side,
  StacksheetLayout,
} from "../types";

export interface SheetPanelProps {
  activeSnapIndex: number;
  Content: ComponentType<Record<string, unknown>> | undefined;
  classNames: ResolvedClassNames;
  close: () => void;
  config: ResolvedConfig;
  depth: number;
  index: number;
  isNested: boolean;
  isTop: boolean;
  item: SheetItem;
  /** On-screen keyboard height (px) to lift bottom sheets above; 0 when inactive. */
  keyboardInset: number;
  layout?: StacksheetLayout;
  onSnap: (index: number) => void;
  pop: () => void;
  prefersReducedMotion: boolean;
  renderHeader?: false | ((props: HeaderRenderProps) => ReactNode);
  shouldRender: boolean;
  side: Side;
  slideFrom: SlideValues;
  slideTarget: SlideValues;
  snapHeights: number[];
  spring: Record<string, unknown>;
  stackSpring: Record<string, unknown>;
  swipeClose: () => void;
  swipePop: () => void;
}
