// vendored from @patternmode/stacksheet@2.0.0 — generated by scripts/build-registry.mjs; do not hand-edit.
import type { ReactNode } from "react";
import type { HeaderRenderProps, StacksheetLayout } from "../types";

export const resolvePanelLayout = (
  layout: StacksheetLayout | undefined,
  renderHeader?: false | ((props: HeaderRenderProps) => ReactNode),
): StacksheetLayout => {
  if (layout) {
    return layout;
  }
  return renderHeader === false ? "composable" : "classic";
};
