// vendored from @patternmode/stacksheet@3.0.0 — generated by scripts/build-registry.mjs; do not hand-edit.
import { FocusTrap } from "focus-trap-react";
import type { ReactNode, RefObject } from "react";
import { useSyncExternalStore } from "react";

// Selectors matched against the focused element to detect when a layer stacked
// on top of the sheet (a nested dialog/popover) has focus, so the sheet's own
// focus trap pauses instead of yanking focus back.
const LAYERED_MODAL_SELECTORS = [
  // Base UI dialogs (e.g. aperto) mark the open popup with `data-open`.
  '[role="dialog"][data-open]',
  '[role="alertdialog"][data-open]',
  // Base UI wraps every floating layer in focus guards.
  "[data-base-ui-focus-guard]",
  // Patternmode popovers whose popup intentionally strips `role="dialog"` to
  // host a combobox/listbox pattern (tags), so they are not caught above.
  '[data-slot="tag-selector-content"]',
  // Third-party Radix content nested inside a sheet still emits these.
  '[role="dialog"][data-state="open"]',
  '[role="alertdialog"][data-state="open"]',
  "[data-radix-popper-content-wrapper]",
  "[data-radix-focus-guard]",
].join(", ");

const subscribeToFocusTarget = (onStoreChange: () => void): (() => void) => {
  document.addEventListener("focusin", onStoreChange, true);
  return () => {
    document.removeEventListener("focusin", onStoreChange, true);
  };
};
const getServerLayeredModalFocused = (): boolean => false;
const getLayeredModalFocused = (): boolean => {
  if (typeof document === "undefined") {
    return false;
  }
  const target = document.activeElement;
  return (
    !!target &&
    target !== document.body &&
    target instanceof Element &&
    target.closest(LAYERED_MODAL_SELECTORS) !== null
  );
};
const useLayeredModalFocused = (active: boolean): boolean => {
  const layered = useSyncExternalStore(
    subscribeToFocusTarget,
    getLayeredModalFocused,
    getServerLayeredModalFocused,
  );
  return active && layered;
};

export const ModalFocusTrap = ({
  enabled,
  active,
  fallbackRef,
  children,
}: {
  enabled: boolean;
  active: boolean;
  fallbackRef: RefObject<HTMLElement | null>;
  children: ReactNode;
}): ReactNode => {
  const paused = useLayeredModalFocused(enabled && active);
  if (!enabled) {
    return children;
  }
  return (
    <FocusTrap
      active={active}
      focusTrapOptions={{
        allowOutsideClick: true,
        escapeDeactivates: false,
        fallbackFocus: () => {
          if (fallbackRef.current !== null) {
            return fallbackRef.current;
          }
          return document.body;
        },
        // Focus the panel element itself (it has tabIndex={-1}) so screen
        // readers announce the dialog when it opens.
        initialFocus: () => fallbackRef.current ?? undefined,
        returnFocusOnDeactivate: true,
      }}
      paused={paused}
    >
      {children}
    </FocusTrap>
  );
};
