// vendored from @patternmode/swatch@1.0.0 — generated by scripts/build-registry.mjs; do not hand-edit.
export {
  DistributionBar,
  type DistributionBarProps,
  type DistributionBarSegment,
  type DistributionBarSegmentUpdate,
  DistributionDisplay,
  type DistributionDisplayProps,
  getDistributionBoundaryPercent,
  getDistributionTotal,
  moveDistributionBoundary,
  removeDistributionSegment,
  updateDistributionSegment,
} from "./DistributionBar";
export {
  getSwatchAtmosphereBackground,
  type SwatchAtmosphereOptions,
} from "./Swatch/swatch-atmosphere";
export { getSwatchColorsBackground } from "./Swatch/swatch-colors";
export { Swatch } from "./Swatch/swatch-root";
export {
  getSwatchSizeVariableStyle,
  SWATCH_SHAPES,
  SWATCH_SIZE_VALUES,
  SWATCH_SIZES,
  SWATCH_TEXTURES,
  type SwatchRenderProps,
  type SwatchColorStop,
  type SwatchDefaultProps,
  type SwatchProps,
  type SwatchShape,
  type SwatchSharedProps,
  type SwatchSize,
  type SwatchTexture,
} from "./Swatch/swatch-types";
