// vendored from @patternmode/swatch@3.0.0 — generated by scripts/build-registry.mjs; do not hand-edit.
export {
  type DistributionBarSegment,
  type DistributionBarSegmentUpdate,
  type DistributionSegment,
  type DistributionSegmentUpdate,
  getDistributionBoundaryPercent,
  getDistributionTotal,
  moveDistributionBoundary,
  removeDistributionSegment,
  updateDistributionSegment,
} from "./Distribution";
export { DistributionBar, type DistributionBarProps } from "./DistributionBar";
export { DistributionDisplay, type DistributionDisplayProps } from "./DistributionDisplay";
export {
  getSwatchAtmosphereBackground,
  type SwatchAtmosphereOptions,
} from "./Swatch/swatch-atmosphere";
export { getSwatchColorsBackground } from "./Swatch/swatch-colors";
export { Swatch } from "./Swatch/swatch-root";
export {
  getSwatchSizeVariableStyle,
  SWATCH_SHAPES,
  SWATCH_SIZE_VALUES,
  SWATCH_SIZES,
  SWATCH_TEXTURES,
  type SwatchRenderProps,
  type SwatchColorStop,
  type SwatchDefaultProps,
  type SwatchProps,
  type SwatchShape,
  type SwatchSharedProps,
  type SwatchSize,
  type SwatchTexture,
} from "./Swatch/swatch-types";
