import next from "@howells/lint/oxlint/next";

export default {
  ...next,
  rules: {
    ...next.rules,
    "eslint/arrow-body-style": "off",
    "eslint/complexity": "off",
    "eslint/default-case": "off",
    "eslint/func-style": "off",
    "eslint/no-bitwise": "off",
    "eslint/no-inline-comments": "off",
    "eslint/no-nested-ternary": "off",
    "eslint/no-plusplus": "off",
    "eslint/no-promise-executor-return": "off",
    "eslint/no-use-before-define": "off",
    "eslint/prefer-destructuring": "off",
    "eslint/require-await": "off",
    "eslint/require-unicode-regexp": "off",
    "eslint/sort-keys": "off",
    "import/consistent-type-specifier-style": "off",
    "import/first": "off",
    "jsdoc/check-tag-names": "off",
    "promise/avoid-new": "off",
    "react-doctor/react-compiler-no-manual-memoization": "off",
    "typescript/array-type": "off",
    "typescript/consistent-type-imports": "off",
    "typescript/no-explicit-any": "off",
    "typescript/no-empty-interface": "off",
    "typescript/no-empty-object-type": "off",
    "unicorn/consistent-function-scoping": "off",
    "unicorn/filename-case": "off",
    "unicorn/no-nested-ternary": "off",
    "unicorn/no-typeof-undefined": "off",
    "unicorn/no-useless-undefined": "off",
    "unicorn/numeric-separators-style": "off",
    "unicorn/prefer-add-event-listener": "off",
    "unicorn/prefer-code-point": "off",
    "unicorn/prefer-logical-operator-over-ternary": "off",
    "unicorn/prefer-math-trunc": "off",
    "unicorn/prefer-modern-math-apis": "off",
    "unicorn/prefer-spread": "off",
    "unicorn/prefer-string-replace-all": "off",
    "unicorn/switch-case-braces": "off",
    "unicorn/text-encoding-identifier-case": "off",
  },
};
