"use client";
// vendored from @patternmode/deck@0.3.4 — generated by scripts/build-registry.mjs; do not hand-edit.

export { CardStack, Deck, DeckCard, DeckEmpty, DeckRoot } from "./deck";
export type { AdvanceDecision, AdvanceDecisionInput } from "./logic";
export {
  getAdvanceDecision,
  getNextDeckIndex,
  getVisibleDeckItems,
  getVisualDepth,
  resolveCardRotation,
} from "./logic";
export type {
  AdvanceDirection,
  DeckAdvanceEvent,
  DeckCardProps,
  DeckEmptyProps,
  DeckItem,
  DeckMode,
  DeckRenderOverlayState,
  DeckRootProps,
} from "./types";
