// vendored from @patternmode/deck@0.3.2 — generated by scripts/build-registry.mjs; do not hand-edit.
import type { AdvanceDirection, DeckItem, DeckMode } from "./types";

export interface AdvanceDecisionInput {
  allowedDirections: AdvanceDirection[];
  /** Pixel threshold, or width ratio when <= 1. */
  distanceThreshold: number;
  offsetX: number;
  /** Horizontal velocity threshold in px/s. */
  velocityThreshold: number;
  velocityX: number;
  width: number;
}

/** Result of evaluating a drag or keyboard advance gesture. */
export interface AdvanceDecision {
  accepted: boolean;
  direction: AdvanceDirection;
}

const normalizeIndex = (index: number, length: number): number =>
  ((index % length) + length) % length;

const hashString = (value: string): number => {
  let hash = 2_166_136_261;

  for (let index = 0; index < value.length; index += 1) {
    hash = (Math.imul(hash, 16_777_619) + (value.codePointAt(index) ?? 0)) % 0xff_ff_ff_ff;
  }

  return Math.abs(hash);
};

/** Returns the visible stack slice, wrapping repeated items only in cycle mode. */
export const getVisibleDeckItems = (
  items: DeckItem[],
  index: number,
  visibleCount: number,
  mode: DeckMode,
): DeckItem[] => {
  if (items.length === 0 || visibleCount <= 0) {
    return [];
  }

  if (mode === "finite") {
    return items.slice(index, index + visibleCount);
  }

  const start = normalizeIndex(index, items.length);
  return Array.from({ length: Math.min(visibleCount, items.length) }, (_, depth) => {
    const itemIndex = (start + depth) % items.length;
    const item = items[itemIndex];

    if (item === undefined) {
      throw new Error("Expected visible deck item to exist.");
    }

    return item;
  });
};

/** Returns the next index, wrapping only in cycle mode. */
export const getNextDeckIndex = (index: number, length: number, mode: DeckMode): number => {
  if (length <= 0) {
    return 0;
  }

  const next = index + 1;
  return mode === "cycle" ? next % length : Math.min(next, length);
};

/** Builds a stable React key that changes each cycle pass for repeated items. */
export const getDeckRenderKey = (
  itemId: string,
  absoluteIndex: number,
  length: number,
  mode: DeckMode,
): string => {
  if (mode !== "cycle" || length <= 0) {
    return itemId;
  }

  return `${itemId}:${Math.floor(absoluteIndex / length)}`;
};

/**
 * Evaluates whether drag distance or velocity should advance a card.
 *
 * Direction is inferred from the dominant horizontal movement, then checked
 * against `allowedDirections`.
 */
export const getAdvanceDecision = (input: AdvanceDecisionInput): AdvanceDecision => {
  const width = Math.max(input.width, 1);
  const distanceThreshold =
    input.distanceThreshold <= 1 ? width * input.distanceThreshold : input.distanceThreshold;
  const distanceAccepted = Math.abs(input.offsetX) >= distanceThreshold;
  const velocityAccepted = Math.abs(input.velocityX) >= input.velocityThreshold;
  const primaryMovement =
    Math.abs(input.offsetX) >= Math.abs(input.velocityX) / 4 ? input.offsetX : input.velocityX;
  const direction: AdvanceDirection = primaryMovement < 0 ? "left" : "right";
  const directionAllowed = input.allowedDirections.includes(direction);

  return {
    accepted: directionAllowed && (distanceAccepted || velocityAccepted),
    direction,
  };
};

/** Resolves deterministic per-card rotation from an item id and spread. */
export const resolveCardRotation = (id: string, spread: number): number => {
  if (spread <= 0) {
    return 0;
  }

  const hash = hashString(id);
  const normalized = hash / 0xff_ff_ff_ff;
  return Number(((normalized * 2 - 1) * spread).toFixed(3));
};

/** Returns the visual depth of an item within the currently visible stack. */
export const getVisualDepth = (item: DeckItem, visibleItems: DeckItem[]): number =>
  visibleItems.findIndex((visibleItem) => visibleItem.id === item.id);
