// vendored from @patternmode/deck@0.4.0 — generated by scripts/build-registry.mjs; do not hand-edit.
import type { HTMLMotionProps } from "motion/react";
import type {
  ComponentPropsWithRef,
  HTMLAttributes,
  KeyboardEventHandler,
  ReactElement,
  ReactNode,
} from "react";

export type DeckMode = "cycle" | "finite";

export type AdvanceDirection = "left" | "right";

/** Normalized child item tracked by Deck's render and advance logic. */
export interface DeckItem {
  element: DeckCardElement;
  id: string;
}

/** Event payload emitted when a card advances. */
export interface DeckAdvanceEvent {
  direction: AdvanceDirection;
  /** Index before the advance is applied. */
  index: number;
  itemId: string;
  mode: DeckMode;
  /** Index after the advance. In finite mode this can equal the item count. */
  nextIndex: number;
}

/** State passed to `renderOverlay` for the active and background cards. */
export interface DeckRenderOverlayState {
  active: boolean;
  depth: number;
  direction: AdvanceDirection | null;
  index: number;
  itemId: string;
}

/** Root deck props for cyclic or finite card stacks. */
export interface DeckRootProps extends Omit<
  ComponentPropsWithRef<"div">,
  "children" | "onDrag" | "onDragEnd" | "onKeyDown"
> {
  /**
   * Directions that can dismiss and advance cards.
   *
   * Default `["left", "right"]`.
   */
  allowedDirections?: AdvanceDirection[];
  children: ReactNode;
  /**
   * Initial active card for uncontrolled decks.
   *
   * Default `0`.
   */
  defaultIndex?: number;
  /**
   * Disables drag, keyboard, and programmatic advance handling.
   *
   * Default `false`.
   */
  disabled?: boolean;
  /**
   * Drag distance threshold. Values less than or equal to 1 are treated as a
   * card-width ratio.
   *
   * Default `0.35`.
   */
  distanceThreshold?: number;
  /**
   * Framer Motion drag elasticity passed to the active card.
   *
   * Default `0.9`.
   */
  dragElastic?: number;
  /** Controlled index. Pair with `onIndexChange`. */
  index?: number;
  /**
   * Cycle wraps forever; finite exhausts into `Deck.Empty`.
   *
   * Default `"cycle"`.
   */
  mode?: DeckMode;
  /** Called once finite mode advances past the final card. */
  onExhausted?: () => void;
  onIndexChange?: (index: number) => void;
  onKeyDown?: KeyboardEventHandler<HTMLInputElement>;
  /** Called when an advance decision is accepted. */
  onAdvance?: (event: DeckAdvanceEvent) => void;
  /** Called after the accepted card's exit animation has completed. */
  onAdvanceEnd?: (event: DeckAdvanceEvent) => void;
  /**
   * Pixel offset between visible background cards.
   *
   * Default `16`.
   */
  peekOffset?: number;
  /**
   * CSS perspective applied to the deck stack.
   *
   * Default `1000`.
   */
  perspective?: number;
  /** Renders per-card overlay content such as labels or progress. */
  renderOverlay?: (state: DeckRenderOverlayState) => ReactNode;
  /**
   * Maximum rotation spread in degrees for stacked cards.
   *
   * Default `6`.
   */
  rotation?: number;
  /**
   * Scale reduction per visible background card.
   *
   * Default `0.045`.
   */
  scaleStep?: number;
  /**
   * Horizontal velocity threshold in px/s.
   *
   * Default `500`.
   */
  velocityThreshold?: number;
  /**
   * Number of cards rendered in the visual stack.
   *
   * Default `3`.
   */
  visibleCount?: number;
}

/**
 * Props for a card rendered by `Deck`.
 *
 * `Deck.Card` renders the children you provide. For image-heavy cards in
 * frameworks like Next.js, put your own optimized image component, such as
 * `next/image` `Image`, inside the card instead of expecting Deck to replace
 * plain `img` elements.
 */
export interface DeckCardProps extends Omit<
  HTMLMotionProps<"div">,
  | "animate"
  | "children"
  | "drag"
  | "dragConstraints"
  | "dragElastic"
  | "dragMomentum"
  | "exit"
  | "initial"
  | "onDrag"
  | "onDragEnd"
  | "onDragStart"
  | "style"
  | "transition"
  | "whileDrag"
> {
  /** Card content rendered unchanged inside the animated deck card. */
  children: ReactNode;
  style?: HTMLAttributes<HTMLDivElement>["style"];
}

export interface DeckEmptyProps extends ComponentPropsWithRef<"div"> {
  children: ReactNode;
}

export type DeckCardElement = ReactElement<DeckCardProps>;
export type DeckEmptyElement = ReactElement<DeckEmptyProps>;
