// vendored from @patternmode/swatch@1.1.1 — generated by scripts/build-registry.mjs; do not hand-edit.
export {
  type DistributionBarSegment,
  type DistributionBarSegmentUpdate,
  getDistributionBoundaryPercent,
  getDistributionTotal,
  moveDistributionBoundary,
  removeDistributionSegment,
  updateDistributionSegment,
} from "./distribution-bar-math";
export {
  DistributionBar,
  type DistributionBarProps,
  DistributionDisplay,
  type DistributionDisplayProps,
} from "./distribution-bar-root";
