"use client";
// vendored from @patternmode/channel@0.2.0 — generated by scripts/build-registry.mjs; do not hand-edit.

import { Slider } from "@base-ui/react/slider";
import { SWATCH_SIZE_VALUES } from "@/components/patternmode/swatch";
import type { SwatchSize } from "@/components/patternmode/swatch";
import type { CSSProperties } from "react";

type ChannelValue = number | readonly [number, number];

/** A horizontal channel. Colour calculation and expensive commit work belong to the app. */
export interface ChannelSliderProps<Value extends ChannelValue = ChannelValue> extends Omit<
  Slider.Root.Props<Value>,
  "children" | "className" | "orientation" | "render" | "style" | "thumbAlignment"
> {
  /** Accessible name; range thumbs append “start” and “end”. */
  label: string;
  /** CSS background, such as a colour gradient. */
  background: string;
  /** Channel height from Swatch's exact size scale. Default: base (32px). */
  size?: SwatchSize;
  labelStart?: string;
  labelEnd?: string;
  /** Names for the two range handles when start/end are not meaningful. */
  thumbLabels?: readonly [string, string];
  /** Ask the app how the thumb should contrast with the colour at this value. */
  getThumbColor?: (value: number, index: number) => string;
  getValueText?: (value: number, index: number) => string;
  className?: string;
  style?: CSSProperties;
}

/** Gradient track with inset glass thumbs; Base UI owns pointer, keyboard and form semantics. */
export const ChannelSlider = <Value extends ChannelValue = number>({
  background,
  className,
  getThumbColor,
  getValueText,
  label,
  labelEnd,
  labelStart,
  size = "base",
  style,
  thumbLabels,
  thumbCollisionBehavior = "none",
  ...props
}: ChannelSliderProps<Value>) => {
  const variables: CSSProperties & Record<`--${string}`, string> = {
    "--patternmode-channel-background": background,
    "--patternmode-channel-size": SWATCH_SIZE_VALUES[size],
    ...style,
  };
  const min = props.min ?? 0;
  const max = props.max ?? 100;
  const share = (value: number) =>
    max <= min ? "0" : String(Math.min(1, Math.max(0, (value - min) / (max - min))));
  const rangeTrack = (
    values: readonly number[],
  ): CSSProperties & Record<`--${string}`, string> => ({
    "--patternmode-channel-end": share(values[1] ?? max),
    "--patternmode-channel-start": share(values[0] ?? min),
    position: "absolute",
  });

  return (
    <Slider.Root
      {...props}
      aria-label={label}
      className={["pm-channel", className].filter(Boolean).join(" ")}
      data-size={size}
      data-slot="channel-slider"
      style={variables}
      thumbAlignment="edge"
      thumbCollisionBehavior={thumbCollisionBehavior}
    >
      <Slider.Control
        className="pm-channel-control"
        data-slot="channel-control"
        render={(controlProps, { values, dragging, activeThumbIndex }) => (
          <div {...controlProps}>
            <Slider.Track
              className={
                values.length === 2
                  ? "pm-channel-track pm-channel-track--range"
                  : "pm-channel-track"
              }
              data-slot="channel-track"
              style={values.length === 2 ? rangeTrack(values) : { position: "absolute" }}
            />
            {values.length === 2 && (
              <Slider.Indicator
                className="pm-channel-aperture"
                data-slot="channel-aperture"
                style={{ position: "absolute" }}
              />
            )}
            {values.map((value, index) => (
              <Slider.Thumb
                key={index === 0 ? "start" : "end"}
                index={index}
                aria-label={
                  values.length === 2
                    ? (thumbLabels?.[index] ?? `${label}, ${index === 0 ? "start" : "end"}`)
                    : label
                }
                getAriaValueText={
                  getValueText
                    ? (_, current, thumbIndex) => getValueText(current, thumbIndex)
                    : undefined
                }
                className="pm-channel-thumb"
                data-slot="channel-thumb"
                data-active-thumb={(dragging && activeThumbIndex === index) || undefined}
              >
                <span className="pm-channel-glass" aria-hidden="true">
                  <span
                    className="pm-channel-core"
                    style={{ background: getThumbColor?.(value, index) }}
                  />
                </span>
              </Slider.Thumb>
            ))}
          </div>
        )}
      />
      {((labelStart ?? "") !== "" || (labelEnd ?? "") !== "") && (
        <div className="pm-channel-labels" aria-hidden="true">
          <span>{labelStart}</span>
          <span>{labelEnd}</span>
        </div>
      )}
    </Slider.Root>
  );
};
