"use client";
// vendored from @patternmode/channel@0.2.1 — generated by scripts/build-registry.mjs; do not hand-edit.
import "./styles.css";

export { ChannelSlider, type ChannelSliderProps } from "./channel-slider";
