// Generates apps/web/lib/art-palettes.ts and the painting crops in
// apps/web/public/art/ from public-domain works at the Art Institute of Chicago.
//
// Run from apps/web:  node scripts/generate-art-palettes.ts
//
// Fetches full IIIF images (square-cropped with object-fit in the demo; the
// server-side `square` region 504s on large paintings) and extracts + names
// palettes with @instruments/colorscope. One-shot generator — its output
// (images + lib/art-palettes.ts) is committed.

import { mkdir, writeFile } from "node:fs/promises";

import { extractColorsFromBuffer } from "@instruments/colorscope/extraction";
import { getColorName, getQuantizedColorName } from "@instruments/colorscope/naming";

interface Artwork {
  artist: string;
  imageId: string;
  slug: string;
  title: string;
  year: string;
}

const UA =
  "PatternmodeColorDemo/1.0 (https://github.com/howells/patternmode; daniel@danielhowells.com)";
const CREDIT = "The Art Institute of Chicago — public domain";
const COLORS_PER_PALETTE = 9;

const ARTWORKS: Artwork[] = [
  {
    artist: "Vincent van Gogh",
    imageId: "6644829f-f292-c5c4-a73c-0356a6fdbf0d",
    slug: "vangogh-bedroom",
    title: "The Bedroom",
    year: "1889",
  },
  {
    artist: "Georges Seurat",
    imageId: "2d484387-2509-5e8e-2c43-22f9981972eb",
    slug: "seurat-grande-jatte",
    title: "A Sunday on La Grande Jatte",
    year: "1884–86",
  },
  {
    artist: "Claude Monet",
    imageId: "3c27b499-af56-f0d5-93b5-a7f2f1ad5813",
    slug: "monet-water-lilies",
    title: "Water Lilies",
    year: "1906",
  },
  {
    artist: "Paul Cézanne",
    imageId: "52ac8996-3460-cf71-cb42-5c4d0aa29b74",
    slug: "cezanne-apples",
    title: "The Basket of Apples",
    year: "1893",
  },
  {
    artist: "Paul Gauguin",
    imageId: "a4bef587-48a4-d186-813d-f297441b1ab3",
    slug: "gauguin-day-of-the-god",
    title: "Mahana no atua (Day of the God)",
    year: "1894",
  },
];

const titleCase = (value: string): string => value.replaceAll(/\b\w/gu, (ch) => ch.toUpperCase());

const fetchImage = async (imageId: string): Promise<Buffer> => {
  const url = `https://www.artic.edu/iiif/2/${imageId}/full/700,/0/default.jpg`;
  const response = await fetch(url, {
    headers: { "AIC-User-Agent": UA, "User-Agent": UA },
    signal: AbortSignal.timeout(25_000),
  });
  if (!response.ok) {
    throw new Error(`Fetch failed (${response.status}) for ${url}`);
  }
  return Buffer.from(await response.arrayBuffer());
};

const artDir = new URL("../public/art/", import.meta.url);

const main = async (): Promise<void> => {
  await mkdir(artDir, { recursive: true });
  const palettes = [];

  for (const art of ARTWORKS) {
    process.stdout.write(`${art.artist} — ${art.title}… `);
    const buffer = await fetchImage(art.imageId);
    await writeFile(new URL(`${art.slug}.jpg`, artDir), buffer);

    const { colors } = await extractColorsFromBuffer(buffer);
    const palette = colors.slice(0, COLORS_PER_PALETTE).map((color, index) => ({
      color: color.hex,
      id: `${art.slug}-${index}`,
      label:
        getQuantizedColorName(color.hex)?.name ??
        titleCase(getColorName(color.hue, color.saturation, color.lightness)),
      value: Number(color.proportion.toFixed(4)),
    }));

    palettes.push({
      artist: art.artist,
      colors: palette,
      credit: CREDIT,
      image: `/art/${art.slug}.jpg`,
      title: art.title,
      year: art.year,
    });
    process.stdout.write(`${palette.length} colors\n`);
  }

  const body = `// Generated by scripts/generate-art-palettes.ts — do not edit by hand.
import type { ParquetTile } from "@patternmode/parquet";

export interface ArtPalette {
  artist: string;
  colors: ParquetTile[];
  credit: string;
  image: string;
  title: string;
  year: string;
}

export const ART_PALETTES: ArtPalette[] = ${JSON.stringify(palettes, null, 2)};
`;
  await writeFile(new URL("../lib/art-palettes.ts", import.meta.url), body);
  console.log(`\nWrote lib/art-palettes.ts (${palettes.length} palettes).`);
};

await main();
