// vendored from @patternmode/stacksheet@2.0.3 — generated by scripts/build-registry.mjs; do not hand-edit.
import { createContext, use } from "react";
import type { StoreApi } from "zustand";
import { useStore } from "zustand";
import { useShallow } from "zustand/react/shallow";
import { resolveConfig } from "./config";
import { SheetRenderer } from "./renderer";
import { SheetPortal } from "./sheet-portal";
import { createSheetStore } from "./store";
import type {
  ResolvedConfig,
  SheetActions,
  StacksheetConfig,
  StacksheetInstance,
  StacksheetProviderProps,
  StacksheetSnapshot,
} from "./types";

type StoreState<TMap extends object> = StacksheetSnapshot<TMap> & SheetActions<TMap>;
/**
 * Create an isolated sheet stack instance with typed store, hooks, and provider.
 *
 * Works with both `interface` and `type` definitions:
 *
 * ```ts
 * // Using an interface
 * interface SheetDataMap {
 *   "bucket-create": { onCreated?: (b: Bucket) => void };
 *   "bucket-edit": { bucket: Bucket };
 * }
 *
 * // Using a type alias
 * type SheetDataMap = {
 *   "bucket-create": { onCreated?: (b: Bucket) => void };
 *   "bucket-edit": { bucket: Bucket };
 * };
 *
 * const { StacksheetProvider, useSheet, useStacksheetState } =
 *   createStacksheet<SheetDataMap>();
 * ```
 *
 * Sheet content components receive their data as **spread props**:
 * ```ts
 * // Data map defines: "bucket-edit": { bucket: Bucket }
 * // Component receives:  ({ bucket }: { bucket: Bucket }) => JSX.Element
 * ```
 *
 * Use `useSheetPanel()` inside content components to access `close()` and `back()`.
 */
export const createStacksheet = <TMap extends object>(
  config?: StacksheetConfig,
): StacksheetInstance<TMap> => {
  const resolved = resolveConfig(config);
  const { store, componentMap } = createSheetStore<TMap>(resolved);
  // Context for the store — allows multiple instances
  const StoreContext = createContext<{
    store: StoreApi<StoreState<TMap>>;
    config: ResolvedConfig;
  } | null>(null);
  const useStoreContext = () => {
    const ctx = use(StoreContext);
    if (!ctx) {
      throw new Error("useSheet/useStacksheetState must be used within <StacksheetProvider>");
    }
    return ctx;
  };
  // ── Provider ────────────────────────────────
  const providerValue = { config: resolved, store };
  const StacksheetProvider = ({
    sheets,
    children,
    classNames,
    layout,
    renderHeader,
  }: StacksheetProviderProps<TMap>) => (
    <StoreContext.Provider value={providerValue}>
      {children}
      <SheetPortal>
        <SheetRenderer<TMap>
          classNames={classNames}
          componentMap={componentMap}
          config={resolved}
          layout={layout}
          renderHeader={renderHeader}
          sheets={sheets}
          store={store}
        />
      </SheetPortal>
    </StoreContext.Provider>
  );
  // ── Hooks ───────────────────────────────────
  const useSheet = (): SheetActions<TMap> => {
    const { store: s } = useStoreContext();
    // Actions are stable refs in Zustand v5 — read once, no subscription needed
    const state = s.getState();
    return {
      close: state.close,
      navigate: state.navigate,
      open: state.open,
      pop: state.pop,
      push: state.push,
      remove: state.remove,
      replace: state.replace,
      setData: state.setData,
      swap: state.swap,
    };
  };
  const useStacksheetState = (): StacksheetSnapshot<TMap> => {
    const { store: s } = useStoreContext();
    return useStore(
      s,
      useShallow((state) => ({
        isOpen: state.isOpen,
        stack: state.stack,
      })),
    );
  };
  return { StacksheetProvider, store, useSheet, useStacksheetState };
};
