// vendored from @patternmode/stacksheet@2.0.0 — generated by scripts/build-registry.mjs; do not hand-edit.
import { useEffect, useState } from "react";
import type { ResolvedConfig, Side } from "./types";
/**
 * Returns true when viewport width is at or below the breakpoint.
 * SSR-safe: defaults to false (desktop).
 */
export const useIsMobile = (breakpoint: number): boolean => {
  const [isMobile, setIsMobile] = useState(false);
  useEffect(() => {
    const mql = window.matchMedia(`(max-width: ${breakpoint - 1}px)`);
    setIsMobile(mql.matches);
    const handler = (e: MediaQueryListEvent) => {
      setIsMobile(e.matches);
    };
    mql.addEventListener("change", handler);
    return () => {
      mql.removeEventListener("change", handler);
    };
  }, [breakpoint]);
  return isMobile;
};
/** Resolve the current side from config + viewport. */
export const useResolvedSide = (config: ResolvedConfig): Side => {
  const isMobile = useIsMobile(config.breakpoint);
  return isMobile ? config.side.mobile : config.side.desktop;
};
