// vendored from @patternmode/stacksheet@2.0.4 — generated by scripts/build-registry.mjs; do not hand-edit.
import type { ReactNode } from "react";
import { useEffect, useState } from "react";
import { createPortal } from "react-dom";

/**
 * Minimal client-only portal into `document.body`. Replaces
 * `@radix-ui/react-portal` — Base UI ships no standalone portal primitive, and
 * the sheet renderer only ever runs on the client. Mounting is deferred to an
 * effect so server render and first client render agree (no hydration
 * mismatch).
 */
export const SheetPortal = ({ children }: { children: ReactNode }): ReactNode => {
  const [mounted, setMounted] = useState(false);
  useEffect(() => {
    setMounted(true);
  }, []);
  if (!mounted || typeof document === "undefined") {
    return null;
  }
  return createPortal(children, document.body);
};
