// vendored from @patternmode/stacksheet@2.0.2 — generated by scripts/build-registry.mjs; do not hand-edit.
import { springs as motionSprings } from "@/lib/patternmode/motion";

import type { SpringConfig } from "./types";

/** Strips the shared token's `type: "spring"` down to Stacksheet's numeric SpringConfig. */
const toSpringConfig = (spring: {
  damping: number;
  mass: number;
  stiffness: number;
}): SpringConfig => ({
  damping: spring.damping,
  mass: spring.mass,
  stiffness: spring.stiffness,
});

/**
 * Spring presets inspired by iOS animation feel.
 *
 * - `subtle` — Barely noticeable bounce, professional. (shared @howells/motion token)
 * - `snappy` — Quick, responsive for interactions. (shared @howells/motion token)
 * - `stiff` — Very quick, controlled. Panels, drawers. **(default)** Intentional
 *   fork: damping 40 (tighter than the shared `stiff`) for drawer control.
 */
export const springs = {
  snappy: toSpringConfig(motionSprings.snappy),
  stiff: { damping: 40, mass: 1, stiffness: 400 },
  subtle: toSpringConfig(motionSprings.subtle),
} satisfies Record<string, SpringConfig>;

export type SpringPreset = keyof typeof springs;
