// vendored from @patternmode/stacksheet@3.0.0 — generated by scripts/build-registry.mjs; do not hand-edit.
import { joinClassNames } from "@/lib/patternmode/system";
import { ArrowLeftIcon } from "../icons";
import { useSheetPanel } from "../panel-context";
import { SheetPartElement } from "./sheet-part-element";
import type { SheetOptionalContentPartProps } from "./sheet-part-types";

export const SheetBack = ({
  render,
  className,
  style,
  children,
}: SheetOptionalContentPartProps) => {
  const { back, isNested } = useSheetPanel();
  if (!isNested) {
    return null;
  }
  const defaults = render
    ? undefined
    : "flex min-h-11 min-w-11 shrink-0 cursor-pointer items-center justify-center rounded-md border-none bg-transparent p-0 text-inherit opacity-60 transition-opacity duration-150 hover:opacity-100";
  return (
    <SheetPartElement
      defaultTagName="button"
      props={{
        "aria-label": children === undefined || children === null ? "Back" : undefined,
        children: children ?? <ArrowLeftIcon />,
        className: joinClassNames(defaults, className),
        onClick: back,
        style,
        type: render ? undefined : "button",
      }}
      render={render}
    />
  );
};
