// vendored from @patternmode/stacksheet@2.0.5 — generated by scripts/build-registry.mjs; do not hand-edit.
import type { CSSProperties, ReactNode } from "react";

import type { RenderProp } from "../render";

export interface SheetPartProps {
  render?: RenderProp;
  children: ReactNode;
  className?: string;
  style?: CSSProperties;
}

export interface SheetOptionalContentPartProps {
  render?: RenderProp;
  children?: ReactNode;
  className?: string;
  style?: CSSProperties;
}

export type SheetBackProps = SheetOptionalContentPartProps;
export type SheetBodyProps = SheetPartProps;
export type SheetCloseProps = SheetOptionalContentPartProps;
export type SheetDescriptionProps = SheetPartProps;
export type SheetFooterProps = SheetPartProps;
export type SheetHandleProps = SheetOptionalContentPartProps;
export type SheetHeaderProps = SheetPartProps;
export type SheetTitleProps = SheetPartProps;
