// vendored from @patternmode/stacksheet@2.0.2 — generated by scripts/build-registry.mjs; do not hand-edit.
import type { JSX } from "react";
import { useRender } from "../render";
import type { RenderProp } from "../render";

/**
 * Renders a sheet part through `render` (or its default tag) via Base UI's
 * `useRender`. Centralising the hook here lets each part early-return before
 * constructing the element without tripping the Rules of Hooks.
 */
export const SheetPartElement = ({
  defaultTagName,
  props,
  render,
}: {
  defaultTagName: keyof JSX.IntrinsicElements;
  props: Record<string, unknown>;
  render: RenderProp | undefined;
}) => useRender({ defaultTagName, props, render });
