// vendored from @patternmode/stacksheet@2.0.5 — generated by scripts/build-registry.mjs; do not hand-edit.
import { joinClassNames } from "@/lib/patternmode/system";
import { XIcon } from "../icons";
import { useSheetPanel } from "../panel-context";
import { SheetPartElement } from "./sheet-part-element";
import type { SheetOptionalContentPartProps } from "./sheet-part-types";

export const SheetClose = ({
  render,
  className,
  style,
  children,
}: SheetOptionalContentPartProps) => {
  const { close } = useSheetPanel();
  const defaults = render
    ? undefined
    : "absolute right-2 top-2 z-20 flex min-h-11 min-w-11 cursor-pointer items-center justify-center rounded-md border-none bg-transparent p-0 text-inherit opacity-50 transition-opacity duration-150 hover:opacity-100";
  return (
    <SheetPartElement
      defaultTagName="button"
      props={{
        "aria-label": children === undefined || children === null ? "Close" : undefined,
        children: children ?? <XIcon />,
        className: joinClassNames(defaults, className),
        onClick: close,
        style,
        type: render ? undefined : "button",
      }}
      render={render}
    />
  );
};
