// vendored from @patternmode/stacksheet@2.0.4 — generated by scripts/build-registry.mjs; do not hand-edit.
import { joinClassNames } from "@/lib/patternmode/system";
import { SheetPartElement } from "./sheet-part-element";
import type { SheetPartProps } from "./sheet-part-types";

export const SheetHeader = ({ render, className, style, children }: SheetPartProps) => {
  // Keep `shrink-0` even in render mode; without it, the header collapses in a
  // flex-column panel layout. No bar, no divider — just a minimal top region.
  const defaults = render ? "shrink-0" : "flex shrink-0 items-center justify-between gap-3";
  return (
    <SheetPartElement
      defaultTagName="header"
      props={{ children, className: joinClassNames(defaults, className), style }}
      render={render}
    />
  );
};
