export {
  SEGMENTED_GAP,
  SEGMENTED_INDICATOR_ACTIVE_CLASS,
  SEGMENTED_INDICATOR_CLASS,
  SEGMENTED_SHELL_BASE,
  SEGMENTED_SHELL_PADDING,
  SEGMENTED_TRIGGER_PADDING,
} from "./segmented-variants";
