export {
  Table,
  TableBody,
  type TableBodyProps,
  TableCaption,
  type TableCaptionProps,
  TableCell,
  type TableCellProps,
  TableFoot,
  type TableFootProps,
  TableHead,
  TableHeaderCell,
  type TableHeaderCellProps,
  type TableHeadProps,
  type TableProps,
  TableRoot,
  type TableRootProps,
  TableRow,
  type TableRowProps,
} from "./component";
export { TablePreview, tablePreviewProps } from "./preview";
