// vendored from @patternmode/stacksheet@2.0.2 — generated by scripts/build-registry.mjs; do not hand-edit.
import { useEffect, useRef } from "react";
import type { RefObject } from "react";
import { findSnapTarget } from "../snap-points";
import { DEAD_ZONE, RUBBER_BAND_FACTOR } from "./drag-constants";
import {
  commitGesture,
  findScrollableAncestor,
  getDismissAxis,
  getPanelDimension,
  isInteractiveElement,
} from "./drag-geometry";
import type { DragConfig, DragState } from "./drag-types";
import { appendVelocitySample, getReleaseVelocity } from "./drag-velocity";
import type { VelocitySample } from "./drag-velocity";

type DragCommit = "drag" | "none";

interface DragRefs {
  committedRef: RefObject<DragCommit | null>;
  offsetRef: RefObject<number>;
  samplesRef: RefObject<VelocitySample[]>;
  scrollTargetRef: RefObject<Element | null>;
  startRef: RefObject<{
    x: number;
    y: number;
  } | null>;
}

const resetDragRefs = ({
  committedRef,
  offsetRef,
  samplesRef,
  scrollTargetRef,
  startRef,
}: DragRefs) => {
  startRef.current = null;
  committedRef.current = null;
  offsetRef.current = 0;
  samplesRef.current = [];
  scrollTargetRef.current = null;
};

const createDragHandlers = ({
  axis,
  config,
  onDragUpdate,
  panelRef,
  refs,
  sign,
}: {
  axis: "x" | "y";
  config: DragConfig;
  onDragUpdate: (state: DragState) => void;
  panelRef: RefObject<HTMLDivElement | null>;
  refs: DragRefs;
  sign: 1 | -1;
}) => {
  const dismiss = () => {
    if (config.isNested) {
      config.onPop();
    } else {
      config.onClose();
    }
  };
  const handlePointerDown = (e: PointerEvent) => {
    if (!config.enabled || e.button !== 0 || !(e.target instanceof Element)) {
      return;
    }
    const { target } = e;
    const isHandle = target.closest("[data-stacksheet-handle]") !== null;
    if (!isHandle && isInteractiveElement(target)) {
      return;
    }
    refs.scrollTargetRef.current = isHandle ? null : findScrollableAncestor(target, axis);
    refs.startRef.current = { x: e.clientX, y: e.clientY };
    refs.committedRef.current = null;
    refs.offsetRef.current = 0;
    refs.samplesRef.current = [{ offset: 0, time: Date.now() }];
    // Pointer capture is deferred until the gesture commits as a drag —
    // capturing here would retarget plain taps away from non-native
    // clickable children (e.g. ARIA-pattern buttons), swallowing their clicks.
  };
  const handlePointerMove = (e: PointerEvent) => {
    if (refs.startRef.current === null) {
      return;
    }
    const dx = e.clientX - refs.startRef.current.x;
    const dy = e.clientY - refs.startRef.current.y;
    const dist = Math.hypot(dx, dy);
    if (refs.committedRef.current === null && dist < DEAD_ZONE) {
      return;
    }
    if (refs.committedRef.current === null) {
      refs.committedRef.current = commitGesture(dx, dy, axis, sign, refs.scrollTargetRef.current);
      if (refs.committedRef.current !== "drag") {
        refs.startRef.current = null;
        return;
      }
      // The gesture is now a real drag — capture so the panel keeps
      // receiving pointer events even when the pointer leaves it.
      if (e.currentTarget instanceof HTMLElement) {
        e.currentTarget.setPointerCapture(e.pointerId);
      }
    }
    if (refs.committedRef.current !== "drag") {
      return;
    }
    const rawOffset = axis === "x" ? dx : dy;
    const directional = rawOffset * sign;
    const clampedOffset =
      directional >= 0 ? directional : -Math.sqrt(Math.abs(directional)) * RUBBER_BAND_FACTOR;
    refs.offsetRef.current = clampedOffset;
    appendVelocitySample(refs.samplesRef.current, { offset: clampedOffset, time: Date.now() });
    onDragUpdate({ isDragging: true, offset: clampedOffset });
    e.preventDefault();
  };
  const handlePointerUp = () => {
    if (refs.startRef.current === null || refs.committedRef.current !== "drag") {
      resetDragRefs(refs);
      return;
    }
    const offset = Math.max(0, refs.offsetRef.current);
    // Release velocity comes from a sliding window of recent samples, so a
    // pause followed by a flick still dismisses (a whole-gesture average
    // would dilute the flick to near zero).
    const velocity = getReleaseVelocity(refs.samplesRef.current, Date.now());
    resetDragRefs(refs);
    const panelSize = getPanelDimension(panelRef.current, axis);
    if (config.snapHeights.length > 0) {
      const targetIndex = findSnapTarget(
        offset,
        panelSize,
        config.snapHeights,
        velocity,
        config.activeSnapIndex,
        config.sequential,
      );
      if (targetIndex === -1) {
        dismiss();
      } else {
        config.onSnap(targetIndex);
        onDragUpdate({ isDragging: false, offset: 0 });
      }
      return;
    }
    const pastThreshold = offset / panelSize > config.closeThreshold;
    const fastEnough = velocity > config.velocityThreshold;
    if (pastThreshold || fastEnough) {
      dismiss();
    } else {
      onDragUpdate({ isDragging: false, offset: 0 });
    }
  };
  const handlePointerCancel = () => {
    resetDragRefs(refs);
    onDragUpdate({ isDragging: false, offset: 0 });
  };
  return { handlePointerCancel, handlePointerDown, handlePointerMove, handlePointerUp };
};

/**
 * Hook that manages drag gestures that can dismiss a sheet panel.
 *
 * Gesture pipeline:
 * 1. Dead zone (10px) — ignores micro-movements
 * 2. Angle check (35°) — must be roughly aligned with dismiss axis
 * 3. Scroll conflict — yields to scrollable containers not at edge
 * 4. Commit — drag is active, applies offset via `onDragUpdate`
 * 5. Release — velocity + threshold determine close/snap/bounce-back
 *
 * Opposite-direction drag uses √(offset) damping for elastic
 * rubber-band resistance (same physics as iOS over-scroll).
 *
 * When `snapHeights` is provided, release targeting uses
 * `findSnapTarget()` instead of the simple threshold check.
 */
export const useDrag = (
  panelRef: RefObject<HTMLDivElement | null>,
  config: DragConfig,
  onDragUpdate: (state: DragState) => void,
) => {
  const startRef = useRef<{
    x: number;
    y: number;
  } | null>(null);
  const committedRef = useRef<DragCommit | null>(null);
  const offsetRef = useRef(0);
  const samplesRef = useRef<VelocitySample[]>([]);
  const scrollTargetRef = useRef<Element | null>(null);
  const { axis, sign } = getDismissAxis(config.side);
  const refs = { committedRef, offsetRef, samplesRef, scrollTargetRef, startRef };
  const { handlePointerCancel, handlePointerDown, handlePointerMove, handlePointerUp } =
    createDragHandlers({ axis, config, onDragUpdate, panelRef, refs, sign });
  const handlersRef = useRef({
    handlePointerCancel,
    handlePointerDown,
    handlePointerMove,
    handlePointerUp,
  });
  handlersRef.current = {
    handlePointerCancel,
    handlePointerDown,
    handlePointerMove,
    handlePointerUp,
  };
  // Attach pointer events to the panel element
  useEffect(() => {
    const el = panelRef.current;
    const onPointerDown = (event: PointerEvent) => {
      handlersRef.current.handlePointerDown(event);
    };
    const onPointerMove = (event: PointerEvent) => {
      handlersRef.current.handlePointerMove(event);
    };
    const onPointerUp = () => {
      handlersRef.current.handlePointerUp();
    };
    const onPointerCancel = () => {
      handlersRef.current.handlePointerCancel();
    };
    const canListen = el !== null && config.enabled;
    if (canListen) {
      el.addEventListener("pointerdown", onPointerDown);
      el.addEventListener("pointermove", onPointerMove);
      el.addEventListener("pointerup", onPointerUp);
      el.addEventListener("pointercancel", onPointerCancel);
    }
    return () => {
      if (canListen) {
        el.removeEventListener("pointerdown", onPointerDown);
        el.removeEventListener("pointermove", onPointerMove);
        el.removeEventListener("pointerup", onPointerUp);
        el.removeEventListener("pointercancel", onPointerCancel);
      }
    };
  }, [panelRef, config.enabled]);
};
