import type { ApertoMediaItem } from "@patternmode/aperto";

export const apertoMedia = [
  {
    alt: "A rammed earth corridor with a ceramic vase and wooden bench between tall slit windows",
    description: "Rammed earth, narrow light slits, and a single vessel.",
    id: "earth-corridor",
    src: "/media/earth-corridor.jpg",
    thumbnailSrc: "/media/earth-corridor.jpg",
    title: "Earth corridor",
    type: "image",
  },
  {
    alt: "A blade of warm light falling across a polished floor from a slit in rammed earth walls",
    description: "A narrow opening cuts a line across polished concrete.",
    id: "light-study",
    src: "/media/light-study.jpg",
    thumbnailSrc: "/media/light-study.jpg",
    title: "Light study",
    type: "image",
  },
  {
    alt: "A rammed earth room with tall vertical windows casting warm light across a built-in bench",
    description: "Earth walls, tall slits, and a low stone bench.",
    id: "rammed-light",
    src: "/media/rammed-light.jpg",
    thumbnailSrc: "/media/rammed-light.jpg",
    title: "Rammed light",
    type: "image",
  },
  {
    alt: "A concrete and clay plaster room with a clerestory window flooding warm light onto a wooden bench",
    description: "Clay plaster meets poured concrete under a clerestory.",
    id: "concrete-room",
    src: "/media/concrete-room.jpg",
    thumbnailSrc: "/media/concrete-room.jpg",
    title: "Concrete room",
    type: "image",
  },
  {
    alt: "Warm afternoon light entering through a vertical slit in a rammed earth wall",
    description: "A single opening washes warm light across earth.",
    id: "slit-window",
    src: "/media/slit-window.jpg",
    thumbnailSrc: "/media/slit-window.jpg",
    title: "Slit window",
    type: "image",
  },
  {
    alt: "A contemplative concrete chamber with a wooden bench beneath a beam of warm daylight",
    description: "Concrete walls, one bench, and a shaft of light.",
    id: "warm-chamber",
    src: "/media/warm-chamber.jpg",
    thumbnailSrc: "/media/warm-chamber.jpg",
    title: "Warm chamber",
    type: "image",
  },
] satisfies ApertoMediaItem[];
