import type { ApertoMediaItem } from "@howells/aperto";

export const apertoMedia = [
	{
		id: "earth-corridor",
		type: "image",
		src: "/media/earth-corridor.jpg",
		thumbnailSrc: "/media/earth-corridor.jpg",
		alt: "A rammed earth corridor with a ceramic vase and wooden bench between tall slit windows",
		title: "Earth corridor",
		description: "Rammed earth, narrow light slits, and a single vessel.",
	},
	{
		id: "light-study",
		type: "image",
		src: "/media/light-study.jpg",
		thumbnailSrc: "/media/light-study.jpg",
		alt: "A blade of warm light falling across a polished floor from a slit in rammed earth walls",
		title: "Light study",
		description: "A narrow opening cuts a line across polished concrete.",
	},
	{
		id: "rammed-light",
		type: "image",
		src: "/media/rammed-light.jpg",
		thumbnailSrc: "/media/rammed-light.jpg",
		alt: "A rammed earth room with tall vertical windows casting warm light across a built-in bench",
		title: "Rammed light",
		description: "Earth walls, tall slits, and a low stone bench.",
	},
	{
		id: "concrete-room",
		type: "image",
		src: "/media/concrete-room.jpg",
		thumbnailSrc: "/media/concrete-room.jpg",
		alt: "A concrete and clay plaster room with a clerestory window flooding warm light onto a wooden bench",
		title: "Concrete room",
		description: "Clay plaster meets poured concrete under a clerestory.",
	},
	{
		id: "slit-window",
		type: "image",
		src: "/media/slit-window.jpg",
		thumbnailSrc: "/media/slit-window.jpg",
		alt: "Warm afternoon light entering through a vertical slit in a rammed earth wall",
		title: "Slit window",
		description: "A single opening washes warm light across earth.",
	},
	{
		id: "warm-chamber",
		type: "image",
		src: "/media/warm-chamber.jpg",
		thumbnailSrc: "/media/warm-chamber.jpg",
		alt: "A contemplative concrete chamber with a wooden bench beneath a beam of warm daylight",
		title: "Warm chamber",
		description: "Concrete walls, one bench, and a shaft of light.",
	},
] satisfies ApertoMediaItem[];
