// Generated by scripts/generate-art-palettes.mjs — do not edit by hand.
import type { ParquetTile } from "@patternmode/parquet";

export interface ArtPalette {
  artist: string;
  colors: ParquetTile[];
  credit: string;
  image: string;
  title: string;
  year: string;
}

export const ART_PALETTES: ArtPalette[] = [
  {
    artist: "Vincent van Gogh",
    colors: [
      {
        color: "#93766c",
        id: "vangogh-bedroom-0",
        label: "Soft Brown",
        value: 0.1548,
      },
      {
        color: "#6c9376",
        id: "vangogh-bedroom-1",
        label: "Muted Green",
        value: 0.1006,
      },
      {
        color: "#6c8093",
        id: "vangogh-bedroom-2",
        label: "Muted Blue",
        value: 0.0962,
      },
      {
        color: "#5980a6",
        id: "vangogh-bedroom-3",
        label: "Muted Blue",
        value: 0.0922,
      },
      {
        color: "#997300",
        id: "vangogh-bedroom-4",
        label: "Mid Yellow",
        value: 0.0768,
      },
      {
        color: "#866913",
        id: "vangogh-bedroom-5",
        label: "Mid Yellow",
        value: 0.0749,
      },
      {
        color: "#808080",
        id: "vangogh-bedroom-6",
        label: "Mid Gray",
        value: 0.0685,
      },
      {
        color: "#9cb3c9",
        id: "vangogh-bedroom-7",
        label: "Soft Blue",
        value: 0.0589,
      },
      {
        color: "#93896c",
        id: "vangogh-bedroom-8",
        label: "Soft Taupe",
        value: 0.0556,
      },
    ],
    credit: "The Art Institute of Chicago — public domain",
    image: "/art/vangogh-bedroom.jpg",
    title: "The Bedroom",
    year: "1889",
  },
  {
    artist: "Georges Seurat",
    colors: [
      {
        color: "#415847",
        id: "seurat-grande-jatte-0",
        label: "Deep Green",
        value: 0.2225,
      },
      {
        color: "#4d4d4d",
        id: "seurat-grande-jatte-1",
        label: "Mid Gray",
        value: 0.1875,
      },
      {
        color: "#808080",
        id: "seurat-grande-jatte-2",
        label: "Mid Gray",
        value: 0.1485,
      },
      {
        color: "#93936c",
        id: "seurat-grande-jatte-3",
        label: "Grayish Yellow",
        value: 0.129,
      },
      {
        color: "#93766c",
        id: "seurat-grande-jatte-4",
        label: "Soft Brown",
        value: 0.075,
      },
      {
        color: "#414758",
        id: "seurat-grande-jatte-5",
        label: "Deep Blue",
        value: 0.0436,
      },
      {
        color: "#b3b3b3",
        id: "seurat-grande-jatte-6",
        label: "Light Gray",
        value: 0.0418,
      },
      {
        color: "#a6a659",
        id: "seurat-grande-jatte-7",
        label: "Warm Yellow",
        value: 0.0356,
      },
      {
        color: "#6c8093",
        id: "seurat-grande-jatte-8",
        label: "Muted Blue",
        value: 0.0355,
      },
    ],
    credit: "The Art Institute of Chicago — public domain",
    image: "/art/seurat-grande-jatte.jpg",
    title: "A Sunday on La Grande Jatte",
    year: "1884–86",
  },
  {
    artist: "Claude Monet",
    colors: [
      {
        color: "#365863",
        id: "monet-water-lilies-0",
        label: "Cool Blue",
        value: 0.1932,
      },
      {
        color: "#5980a6",
        id: "monet-water-lilies-1",
        label: "Muted Blue",
        value: 0.1489,
      },
      {
        color: "#6c8093",
        id: "monet-water-lilies-2",
        label: "Muted Blue",
        value: 0.1369,
      },
      {
        color: "#364d63",
        id: "monet-water-lilies-3",
        label: "Deep Blue",
        value: 0.1105,
      },
      {
        color: "#366363",
        id: "monet-water-lilies-4",
        label: "Grayish Teal",
        value: 0.07,
      },
      {
        color: "#5993a6",
        id: "monet-water-lilies-5",
        label: "Muted Blue",
        value: 0.0665,
      },
      {
        color: "#6c9393",
        id: "monet-water-lilies-6",
        label: "Mid Teal",
        value: 0.0575,
      },
      {
        color: "#266073",
        id: "monet-water-lilies-7",
        label: "Cool Blue",
        value: 0.0355,
      },
      {
        color: "#264d73",
        id: "monet-water-lilies-8",
        label: "Deep Blue",
        value: 0.0265,
      },
    ],
    credit: "The Art Institute of Chicago — public domain",
    image: "/art/monet-water-lilies.jpg",
    title: "Water Lilies",
    year: "1906",
  },
  {
    artist: "Paul Cézanne",
    colors: [
      {
        color: "#808080",
        id: "cezanne-apples-0",
        label: "Mid Gray",
        value: 0.2534,
      },
      {
        color: "#4d4d4d",
        id: "cezanne-apples-1",
        label: "Mid Gray",
        value: 0.1417,
      },
      {
        color: "#beb8a7",
        id: "cezanne-apples-2",
        label: "Warm Beige",
        value: 0.1279,
      },
      {
        color: "#634d36",
        id: "cezanne-apples-3",
        label: "Warm Brown",
        value: 0.1142,
      },
      {
        color: "#635836",
        id: "cezanne-apples-4",
        label: "Warm Brown",
        value: 0.0586,
      },
      {
        color: "#6c9380",
        id: "cezanne-apples-5",
        label: "Mid Teal",
        value: 0.0568,
      },
      {
        color: "#a68059",
        id: "cezanne-apples-6",
        label: "Muted Orange",
        value: 0.0442,
      },
      {
        color: "#734d26",
        id: "cezanne-apples-7",
        label: "Warm Brown",
        value: 0.0385,
      },
      {
        color: "#93896c",
        id: "cezanne-apples-8",
        label: "Soft Taupe",
        value: 0.0313,
      },
    ],
    credit: "The Art Institute of Chicago — public domain",
    image: "/art/cezanne-apples.jpg",
    title: "The Basket of Apples",
    year: "1893",
  },
  {
    artist: "Paul Gauguin",
    colors: [
      {
        color: "#364d63",
        id: "gauguin-day-of-the-god-0",
        label: "Deep Blue",
        value: 0.0763,
      },
      {
        color: "#936c6c",
        id: "gauguin-day-of-the-god-1",
        label: "Muted Red",
        value: 0.0672,
      },
      {
        color: "#4d4d4d",
        id: "gauguin-day-of-the-god-2",
        label: "Mid Gray",
        value: 0.0609,
      },
      {
        color: "#0d1a26",
        id: "gauguin-day-of-the-god-3",
        label: "Dark Blue",
        value: 0.0599,
      },
      {
        color: "#a6596c",
        id: "gauguin-day-of-the-god-4",
        label: "Mid Pink",
        value: 0.0465,
      },
      {
        color: "#264d73",
        id: "gauguin-day-of-the-god-5",
        label: "Deep Blue",
        value: 0.0429,
      },
      {
        color: "#365863",
        id: "gauguin-day-of-the-god-6",
        label: "Cool Blue",
        value: 0.0406,
      },
      {
        color: "#bf8040",
        id: "gauguin-day-of-the-god-7",
        label: "Warm Orange",
        value: 0.0357,
      },
      {
        color: "#808080",
        id: "gauguin-day-of-the-god-8",
        label: "Mid Gray",
        value: 0.0341,
      },
    ],
    credit: "The Art Institute of Chicago — public domain",
    image: "/art/gauguin-day-of-the-god.jpg",
    title: "Mahana no atua (Day of the God)",
    year: "1894",
  },
];
