// vendored from @patternmode/swatch@3.0.0 — generated by scripts/build-registry.mjs; do not hand-edit.
import { PATTERNMODE_SIZE_VALUES, PATTERNMODE_SIZES } from "@/lib/patternmode/system";
import type { ObjectFit } from "@/lib/patternmode/system";
import type { ComponentType, HTMLAttributes, ReactNode, SVGProps } from "react";

import type { RenderProp } from "../render";

export const SWATCH_SIZES = [...PATTERNMODE_SIZES, "4xl", "5xl", "6xl", "7xl"] as const;

export const SWATCH_SIZE_VALUES = {
  ...PATTERNMODE_SIZE_VALUES,
  "4xl": "4.5rem",
  "5xl": "5rem",
  "6xl": "5.5rem",
  "7xl": "6rem",
} as const satisfies Record<SwatchSize, string>;

export const SWATCH_SHAPES = ["circle", "pill", "square", "block"] as const;

export const SWATCH_TEXTURES = ["atmosphere"] as const;

export type SwatchSize = (typeof SWATCH_SIZES)[number];
export type SwatchShape = (typeof SWATCH_SHAPES)[number];
export type SwatchTexture = (typeof SWATCH_TEXTURES)[number];
export type SwatchColorStop = string | { color: string; ratio?: number };
type SwatchIcon = ComponentType<SVGProps<SVGSVGElement>>;

export const getSwatchSizeVariableStyle = (
  size: SwatchSize,
  variableName = "--patternmode-swatch-size",
): Record<string, string> => ({
  [variableName]: SWATCH_SIZE_VALUES[size],
});

/**
 * Visual and behavioural props shared by every Swatch rendering mode. These
 * map deterministically to the fill, scrim, shape, and size treatment
 * regardless of whether the swatch renders its own wrapper or a `render`
 * element.
 */
export interface SwatchSharedProps extends HTMLAttributes<HTMLElement> {
  background?: string;
  color?: string;
  /**
   * How multiple `colors` blend: `"step"` renders hard bands, `"smooth"`
   * renders a continuous OKLab-interpolated ramp. Ignored by
   * `texture="atmosphere"`.
   *
   * Default `"step"`.
   */
  blend?: "smooth" | "step";
  colors?: SwatchColorStop[];
  /**
   * Atmosphere density (0 = diffuse wash, 1 = dense pools). Only applies when
   * `texture="atmosphere"`.
   *
   * Default `0.5`.
   */
  density?: number;
  /**
   * Render a precise, flat color block: no top-to-bottom scrim gradient and
   * no drop shadow. Use for data visualisation where the fill must read as
   * the exact color value.
   *
   * Default `false`.
   */
  flat?: boolean;
  /**
   * Atmosphere gravity (-1 = pools sink, 1 = pools rise). Only applies when
   * `texture="atmosphere"`.
   *
   * Default `0`.
   */
  gravity?: number;
  icon?: SwatchIcon;
  isLight?: boolean;
  /**
   * Object-fit mode applied to media children through CSS variables.
   *
   * Default `"cover"`.
   */
  objectFit?: ObjectFit;
  /**
   * Object-position value applied to media children through CSS variables.
   *
   * Default `"center"`.
   */
  objectPosition?: string;
  raised?: boolean;
  /**
   * Shows selected state and optional icon overlay.
   *
   * Default `false`.
   */
  selected?: boolean;
  /**
   * Rendered swatch shape.
   *
   * Default `"circle"`.
   */
  shape?: SwatchShape;
  /**
   * Whether selected swatches render their ring treatment.
   *
   * Default `true`.
   */
  showRing?: boolean;
  /**
   * Size token used for the swatch dimensions.
   *
   * Default `"base"`.
   */
  size?: SwatchSize;
  /**
   * Render supplied colors as a soft, layered radial atmosphere — overlapping
   * color pools — instead of a ratio-encoded weighted palette. Pair with
   * `density` and `gravity` to shape the pools.
   */
  texture?: SwatchTexture;
  /**
   * Marks the swatch as unavailable.
   *
   * Default `false`.
   */
  unavailable?: boolean;
}

/**
 * Default Swatch props: the swatch renders its own wrapper element
 * (`<figure>`, or `<fieldset>` when `onRemove` is set).
 */
export interface SwatchDefaultProps extends SwatchSharedProps {
  render?: undefined;
  /**
   * Optional media rendered inside the swatch frame.
   *
   * Swatch does not optimize image elements itself. Next.js consumers can pass
   * their own `next/image` `Image` component here and use `objectFit` /
   * `objectPosition` to align it with the swatch shape.
   */
  children?: ReactNode;
  /** Renders a remove affordance and calls this after stopping propagation. */
  onRemove?: () => void;
  /** Accessible label for the remove affordance. Defaults to the swatch label. */
  removeLabel?: string;
}

/**
 * `render` Swatch props: the swatch merges its className, style (size/fill
 * CSS variables), data attributes, and other props onto the element passed via
 * `render`, rendering through it (Base UI render-prop pattern) instead of
 * emitting its own wrapper. Use this when the swatch must *be* an interactive
 * element, such as a `<button>` cell in a color matrix.
 *
 * The `render` element must be childless — put the swatch's content in
 * `children`, e.g. `<Swatch render={<button type="button" />}>A1</Swatch>`.
 * Children on the `render` element itself would override the swatch's own fill
 * layers.
 *
 * `onRemove` is unsupported in this mode — its remove affordance cannot be
 * composed into an arbitrary rendered element. Wrap a default Swatch instead
 * when a remove control is required.
 */
export interface SwatchRenderProps extends SwatchSharedProps {
  render: RenderProp;
  children?: ReactNode;
  onRemove?: never;
  removeLabel?: never;
}

export type SwatchProps = SwatchDefaultProps | SwatchRenderProps;
