// vendored from @patternmode/swatch@4.0.0 — generated by scripts/build-registry.mjs; do not hand-edit.
import { joinClassNames, sanitizeWeight } from "@/lib/patternmode/system";
import type { HTMLAttributes } from "react";
import {
  getDerivedDistributionPercentage,
  getDistributionTotal,
} from "../Distribution/distribution-math";
import type { DistributionSegment } from "../Distribution/distribution-math";
import {
  DistributionSegmentLegend,
  DistributionSegments,
} from "../Distribution/distribution-parts";

export interface DistributionDisplayProps extends Omit<
  HTMLAttributes<HTMLElement>,
  "role" | "onSelect"
> {
  /** Label used in summary legends for assigned segment weight. */
  assignedLabel?: string;
  /** Label used when `emptyValue` contributes unassigned weight. */
  emptyLabel?: string;
  /**
   * Extra unassigned weight included in derived percentage calculations.
   *
   * Default `0`.
   */
  emptyValue?: number;
  /**
   * Legend style for the read-only display.
   *
   * Default `"segments"`.
   */
  legend?: "segments" | "summary" | false;
  /**
   * When provided, each segment renders as a button and selecting one
   * invokes this callback. Pair with `selectedSegmentId` to mark a segment
   * as selected (renders a ring). Read-only by default.
   */
  onSegmentSelect?: (segment: DistributionSegment) => void;
  segments: DistributionSegment[];
  /** Id of the selected segment — renders a ring on that segment. */
  selectedSegmentId?: string;
}

interface DistributionSummaryLegendProps {
  assignedLabel: string;
  emptyLabel: string;
  emptyValue: number;
  total: number;
}

const getDistributionDisplayTotal = (segments: DistributionSegment[], emptyValue: number): number =>
  getDistributionTotal(segments) + sanitizeWeight(emptyValue);

const getDistributionDisplayAccessibleLabel = (
  segments: DistributionSegment[],
  emptyValue: number,
  emptyLabel: string,
  total: number,
): string => {
  const segmentLabels = segments.map(
    (segment) =>
      `${segment.label ?? segment.id} ${getDerivedDistributionPercentage(segment.value, total)}%`,
  );
  if (emptyValue > 0) {
    segmentLabels.push(`${emptyLabel} ${getDerivedDistributionPercentage(emptyValue, total)}%`);
  }

  return segmentLabels.join(", ");
};

const DistributionSummaryLegend = ({
  assignedLabel,
  emptyLabel,
  emptyValue,
  total,
}: DistributionSummaryLegendProps) => {
  const emptyPercentage = getDerivedDistributionPercentage(emptyValue, total);

  return (
    <div className="patternmode-distribution-bar__legend">
      <span>
        {Math.max(0, 100 - emptyPercentage)}% {assignedLabel}
      </span>
      {emptyValue > 0 ? (
        <span>
          {emptyPercentage}% {emptyLabel}
        </span>
      ) : null}
    </div>
  );
};

/**
 * A read-only proportional strip: one bordered track of contiguous weighted
 * segments, with an optional legend.
 *
 * **Not an editor.** `DistributionBar` is the editor — it renders `role="slider"`
 * handles and mutates its segments. This one draws them and nothing else, which
 * is the right shape when the weights were computed rather than allocated by a
 * human: dragging the edge of a bucket a computation filled just lies.
 *
 * It lives in its own directory for that reason. It used to be filed inside
 * `DistributionBar/` and exported from the editor's barrel, and the result was
 * that two separate consumers looked for a read-only distribution strip, did not
 * find one, and reported the territory unserved.
 *
 * Contiguity is the point: one track with hairline boundaries, not a flex row of
 * individually-rounded `Swatch` blocks, which leaks each swatch's own radius and
 * shadow as seams.
 *
 * Pass `onSegmentSelect` to make each segment a button — selection is still not
 * editing, so the element stays a `figure` unless it becomes interactive.
 */
export const DistributionDisplay = ({
  "aria-label": ariaLabel,
  assignedLabel = "assigned",
  className,
  emptyLabel = "unassigned",
  emptyValue = 0,
  legend = "segments",
  onSegmentSelect,
  segments,
  selectedSegmentId,
  ...props
}: DistributionDisplayProps) => {
  const total = getDistributionDisplayTotal(segments, emptyValue);
  const interactive = Boolean(onSegmentSelect);
  const accessibleLabel =
    ariaLabel ?? getDistributionDisplayAccessibleLabel(segments, emptyValue, emptyLabel, total);

  const content = (
    <>
      <div className="patternmode-distribution-bar__track">
        <DistributionSegments
          emptyValue={emptyValue}
          onSegmentSelect={onSegmentSelect}
          segments={segments}
          selectedSegmentId={selectedSegmentId}
          total={total}
        />
      </div>
      {legend === "segments" ? (
        <DistributionSegmentLegend
          emptyLabel={emptyLabel}
          emptyValue={emptyValue}
          segments={segments}
          total={total}
        />
      ) : null}
      {legend === "summary" ? (
        <DistributionSummaryLegend
          assignedLabel={assignedLabel}
          emptyLabel={emptyLabel}
          emptyValue={emptyValue}
          total={total}
        />
      ) : null}
    </>
  );
  const sharedClassName = joinClassNames("patternmode-distribution-display", className);

  return interactive ? (
    <fieldset
      {...props}
      aria-label={accessibleLabel}
      className={sharedClassName}
      data-slot="distribution-display"
    >
      {content}
    </fieldset>
  ) : (
    <figure
      {...props}
      aria-label={accessibleLabel}
      className={sharedClassName}
      data-slot="distribution-display"
    >
      {content}
    </figure>
  );
};
