// vendored from @patternmode/deck@0.3.4 — generated by scripts/build-registry.mjs; do not hand-edit.
import { joinClassNames } from "@/lib/patternmode/system";

import type { DeckEmptyProps } from "../types";

export const DeckEmpty = ({ children, className, ref, ...props }: DeckEmptyProps) => (
  <div {...props} className={joinClassNames("patternmode-deck-empty", className)} ref={ref}>
    {children}
  </div>
);

DeckEmpty.displayName = "Deck.Empty";
