// vendored from @patternmode/deck@0.3.2 — generated by scripts/build-registry.mjs; do not hand-edit.
import type { DeckCardProps } from "../types";

export const DeckCard = (_props: DeckCardProps) => null;

DeckCard.displayName = "Deck.Card";
