"use client";
// vendored from @patternmode/deck@0.5.1 — generated by scripts/build-registry.mjs; do not hand-edit.

import { joinClassNames } from "@/lib/patternmode/system";
import { AnimatePresence, domMax, LazyMotion, m, useReducedMotion } from "motion/react";
import { useEffect, useId, useReducer, useRef } from "react";
import type { CSSProperties } from "react";

import { getDeckRenderKey, getVisibleDeckItems, resolveCardRotation } from "../logic";
import type {
  AdvanceDirection,
  DeckEnterMode,
  DeckItem,
  DeckMode,
  DeckRenderOverlayState,
  DeckRootProps,
} from "../types";
import { DeckCard } from "./deck-card";
import {
  BG_RESPONSE_FACTOR,
  BG_RESPONSE_RAMP,
  CARD_DEFAULT_SPRING,
  CARD_ENTER_OFFSET,
  CARD_ENTER_SCALE,
  CARD_ROTATE_SPRING,
  CARD_SCALE_SPRING,
  CARD_Y_SPRING,
  DEFAULT_DIRECTIONS,
  DEFAULT_DISTANCE_THRESHOLD,
  DEFAULT_DRAG_ELASTIC,
  DEFAULT_ENTER,
  DEFAULT_PEEK_OFFSET,
  DEFAULT_PERSPECTIVE,
  DEFAULT_ROTATION,
  DEFAULT_SCALE_STEP,
  DEFAULT_VELOCITY_THRESHOLD,
  DEFAULT_VISIBLE_COUNT,
  DRAG_INFLUENCE_RAMP,
  DRAG_TILT_MAX,
  DRAG_TILT_RAMP,
} from "./deck-constants";
import { DeckEmpty } from "./deck-empty";
import { cardExitVariants } from "./deck-motion";
import { useDeckChildren } from "./use-deck-children";
import { createDeckState, deckReducer, useDeckInteractions } from "./use-deck-interactions";
import type { DeckInteractions } from "./use-deck-interactions";

interface DeckRenderedCardProps {
  activeIndex: number;
  depth: number;
  disabled: boolean;
  dragElastic: number;
  dragOffset: number;
  dragProgress: number;
  /** True when this card joined the visible stack after the deck first rendered. */
  entering: boolean;
  exitCustom: { direction: AdvanceDirection | null; velocity: number };
  interactions: DeckInteractions;
  isDragging: boolean;
  item: DeckItem;
  lastDirection: AdvanceDirection | null;
  peekOffset: number;
  reduceMotion: boolean;
  renderOverlay: DeckRootProps["renderOverlay"];
  rotation: number;
  scaleStep: number;
  visibleCount: number;
}

interface DeckRenderedCardsProps {
  activeIndex: number;
  cardsLength: number;
  disabled: boolean;
  dragElastic: number;
  dragOffset: number;
  dragProgress: number;
  enteringIds: ReadonlySet<string>;
  exitCustom: { direction: AdvanceDirection | null; velocity: number };
  interactions: DeckInteractions;
  isDragging: boolean;
  lastDirection: AdvanceDirection | null;
  mode: DeckMode;
  peekOffset: number;
  reduceMotion: boolean;
  renderOverlay: DeckRootProps["renderOverlay"];
  rotation: number;
  scaleStep: number;
  visibleCards: DeckItem[];
  visualBaseIndex: number;
}

const getAbsoluteVisualIndex = (
  mode: DeckMode,
  visualBaseIndex: number,
  activeIndex: number,
  depth: number,
) => (mode === "cycle" ? visualBaseIndex : activeIndex) + depth;

const withDefault = <T,>(value: T | undefined, fallback: T): T => value ?? fallback;

const getCardRotationValue = (
  active: boolean,
  isDragging: boolean,
  reduceMotion: boolean,
  dragOffset: number,
  idleRotate: number,
) => {
  if (!active || !isDragging || reduceMotion) {
    return idleRotate;
  }

  const influence = Math.min(1, Math.abs(dragOffset) / DRAG_INFLUENCE_RAMP);
  const tilt = (dragOffset / DRAG_TILT_RAMP) * DRAG_TILT_MAX;

  return Number((idleRotate * (1 - influence) + tilt).toFixed(3));
};

const getCardDepthMotion = (
  active: boolean,
  isDragging: boolean,
  reduceMotion: boolean,
  depth: number,
  dragProgress: number,
  peekOffset: number,
  scaleStep: number,
) => {
  const restScale = reduceMotion ? 1 : Math.max(0.7, 1 - depth * scaleStep);
  const restY = reduceMotion ? 0 : depth * peekOffset;

  if (active || !isDragging || reduceMotion) {
    return { scale: restScale, y: restY };
  }

  const promotedScale = Math.max(0.7, 1 - (depth - 1) * scaleStep);
  const promotedY = (depth - 1) * peekOffset;

  return {
    scale: restScale + (promotedScale - restScale) * dragProgress * BG_RESPONSE_FACTOR,
    y: restY + (promotedY - restY) * dragProgress * BG_RESPONSE_FACTOR,
  };
};

/**
 * Where an entering card starts: a little beneath and behind its rest pose, so
 * it settles up into the stack on the same springs the stack already uses.
 * Reduced motion fades only.
 */
const getCardEnterInitial = (
  entering: boolean,
  reduceMotion: boolean,
  idleRotate: number,
  rest: { scale: number; y: number },
) => {
  if (!entering) {
    return false;
  }

  if (reduceMotion) {
    return { opacity: 0 };
  }

  return {
    opacity: 0,
    rotate: idleRotate,
    scale: rest.scale * CARD_ENTER_SCALE,
    y: rest.y + CARD_ENTER_OFFSET,
  };
};

const getRotateTransition = (active: boolean, isDragging: boolean) => {
  if (isDragging && active) {
    return { duration: 0 };
  }

  return CARD_ROTATE_SPRING;
};

const getWhileDrag = (draggable: boolean, reduceMotion: boolean) =>
  draggable
    ? {
        cursor: "grabbing",
        scale: reduceMotion ? 1 : 1.02,
      }
    : undefined;

const getDeckControlProps = ({
  ariaLabel,
  ariaLabelledBy,
  activeIndex,
  itemId,
  total,
}: {
  ariaLabel: string | undefined;
  ariaLabelledBy: string | undefined;
  activeIndex: number;
  itemId: string | undefined;
  total: number;
}) => {
  const valueMax = Math.max(total - 1, 0);
  const valueNow = Math.min(Math.max(activeIndex, 0), valueMax);

  return {
    "aria-label": ariaLabel,
    "aria-labelledby": ariaLabelledBy,
    "aria-valuetext": itemId ?? "No cards",
    max: valueMax,
    min: 0,
    readOnly: true,
    type: "range" as const,
    value: valueNow,
  };
};

const getDeckRootDataProps = (disabled: boolean, exhausted: boolean) => ({
  "data-disabled": disabled ? "true" : undefined,
  "data-empty": exhausted ? "true" : undefined,
});

const DeckRenderedCard = ({
  activeIndex,
  depth,
  disabled,
  dragElastic,
  dragOffset,
  dragProgress,
  entering,
  exitCustom,
  interactions,
  isDragging,
  item,
  lastDirection,
  peekOffset,
  reduceMotion,
  renderOverlay,
  rotation,
  scaleStep,
  visibleCount,
}: DeckRenderedCardProps) => {
  const active = depth === 0;
  const card = item.element;
  const cardProps = card.props;
  const cardStyle = {
    ...cardProps.style,
    "--deck-depth": depth,
  } as CSSProperties;
  const draggable = active && !disabled;
  const overlayState: DeckRenderOverlayState = {
    active,
    depth,
    direction: lastDirection,
    index: activeIndex + depth,
    itemId: item.id,
  };
  const idleRotate = reduceMotion ? 0 : resolveCardRotation(item.id, rotation);
  const cardRotate = getCardRotationValue(active, isDragging, reduceMotion, dragOffset, idleRotate);
  const cardMotion = getCardDepthMotion(
    active,
    isDragging,
    reduceMotion,
    depth,
    dragProgress,
    peekOffset,
    scaleStep,
  );
  const enterInitial = getCardEnterInitial(entering, reduceMotion, idleRotate, cardMotion);
  const consumerRef = cardProps.ref;
  const attachCardRef = (node: HTMLDivElement | null) => {
    // Track the mounted active card so drag gestures can measure its width.
    // Never clear on `null`: an exiting clone unmounts after its replacement
    // has attached and must not clobber the live reference.
    if (active && node !== null) {
      interactions.activeCardRef.current = node;
    }

    if (typeof consumerRef === "function") {
      consumerRef(node);
    } else if (consumerRef !== null && consumerRef !== undefined) {
      consumerRef.current = node;
    }
  };

  return (
    <m.div
      {...cardProps}
      aria-hidden={active ? undefined : true}
      animate={{
        opacity: 1,
        rotate: cardRotate,
        scale: active ? 1 : cardMotion.scale,
        y: active ? 0 : cardMotion.y,
        zIndex: visibleCount - depth,
      }}
      className={joinClassNames("patternmode-deck-card", cardProps.className)}
      custom={exitCustom}
      data-active={active ? "true" : "false"}
      data-depth={depth}
      data-direction={lastDirection ?? undefined}
      drag={active && !disabled ? "x" : false}
      dragConstraints={{ left: 0, right: 0 }}
      dragElastic={dragElastic}
      dragMomentum={true}
      dragTransition={{
        bounceDamping: 22,
        bounceStiffness: 300,
        power: 0.3,
        timeConstant: 350,
      }}
      exit="exit"
      inert={active ? undefined : true}
      initial={enterInitial}
      onDrag={draggable ? interactions.handleDrag : undefined}
      onDragEnd={draggable ? interactions.handleDragEnd : undefined}
      onDragStart={draggable ? interactions.handleDragStart : undefined}
      ref={attachCardRef}
      style={cardStyle}
      transition={{
        default: CARD_DEFAULT_SPRING,
        opacity: { duration: 0.2, ease: "easeOut" },
        rotate: getRotateTransition(active, isDragging),
        scale: CARD_SCALE_SPRING,
        y: CARD_Y_SPRING,
      }}
      variants={cardExitVariants}
      whileDrag={getWhileDrag(draggable, reduceMotion)}
    >
      {cardProps.children}
      {renderOverlay?.(overlayState)}
    </m.div>
  );
};

const DeckRenderedCards = ({
  activeIndex,
  cardsLength,
  disabled,
  dragElastic,
  dragOffset,
  dragProgress,
  enteringIds,
  exitCustom,
  interactions,
  isDragging,
  lastDirection,
  mode,
  peekOffset,
  reduceMotion,
  renderOverlay,
  rotation,
  scaleStep,
  visibleCards,
  visualBaseIndex,
}: DeckRenderedCardsProps) => (
  <LazyMotion features={domMax}>
    <AnimatePresence
      custom={exitCustom}
      initial={false}
      onExitComplete={interactions.handleExitComplete}
    >
      {visibleCards.map((item, depth) => (
        <DeckRenderedCard
          activeIndex={activeIndex}
          depth={depth}
          disabled={disabled}
          dragElastic={dragElastic}
          dragOffset={dragOffset}
          dragProgress={dragProgress}
          entering={enteringIds.has(item.id)}
          exitCustom={exitCustom}
          interactions={interactions}
          isDragging={isDragging}
          item={item}
          key={getDeckRenderKey(
            item.id,
            getAbsoluteVisualIndex(mode, visualBaseIndex, activeIndex, depth),
            cardsLength,
            mode,
          )}
          lastDirection={lastDirection}
          peekOffset={peekOffset}
          reduceMotion={reduceMotion}
          renderOverlay={renderOverlay}
          rotation={rotation}
          scaleStep={scaleStep}
          visibleCount={visibleCards.length}
        />
      ))}
    </AnimatePresence>
  </LazyMotion>
);

/**
 * Ids of visible cards the deck has never shown before, excluding the first
 * render. A card stays "entering" for the render it mounts in and is then
 * remembered, so a cycle-mode repeat or a promotion never re-enters.
 */
const useEnteringCardIds = (
  visibleCards: DeckItem[],
  enter: DeckEnterMode,
): ReadonlySet<string> => {
  const shownIds = useRef<Set<string> | null>(null);
  const entering = new Set<string>();

  if (shownIds.current === null) {
    shownIds.current = new Set(visibleCards.map((item) => item.id));
  } else if (enter !== "none") {
    for (const item of visibleCards) {
      if (!shownIds.current.has(item.id)) {
        entering.add(item.id);
      }
    }
  }

  useEffect(() => {
    for (const item of visibleCards) {
      shownIds.current?.add(item.id);
    }
  });

  return entering;
};

type DeckTuning = Pick<
  DeckRootProps,
  | "allowedDirections"
  | "defaultIndex"
  | "disabled"
  | "distanceThreshold"
  | "dragElastic"
  | "enter"
  | "mode"
  | "peekOffset"
  | "perspective"
  | "rotation"
  | "scaleStep"
  | "velocityThreshold"
  | "visibleCount"
>;

/** Pulls the tuning props off the rest bag, applies defaults, and returns what is left for the root div. */
const splitDeckTuning = <T extends DeckTuning>(rest: T) => {
  const {
    allowedDirections,
    defaultIndex,
    disabled,
    distanceThreshold,
    dragElastic,
    enter,
    mode,
    peekOffset,
    perspective,
    rotation,
    scaleStep,
    velocityThreshold,
    visibleCount,
    ...props
  } = rest;

  return {
    props,
    tuning: {
      allowedDirections: withDefault(allowedDirections, DEFAULT_DIRECTIONS),
      defaultIndex: withDefault(defaultIndex, 0),
      disabled: withDefault(disabled, false),
      distanceThreshold: withDefault(distanceThreshold, DEFAULT_DISTANCE_THRESHOLD),
      dragElastic: withDefault(dragElastic, DEFAULT_DRAG_ELASTIC),
      enter: withDefault<DeckEnterMode>(enter, DEFAULT_ENTER),
      mode: withDefault<DeckMode>(mode, "cycle"),
      peekOffset: withDefault(peekOffset, DEFAULT_PEEK_OFFSET),
      perspective: withDefault(perspective, DEFAULT_PERSPECTIVE),
      rotation: withDefault(rotation, DEFAULT_ROTATION),
      scaleStep: withDefault(scaleStep, DEFAULT_SCALE_STEP),
      velocityThreshold: withDefault(velocityThreshold, DEFAULT_VELOCITY_THRESHOLD),
      visibleCount: withDefault(visibleCount, DEFAULT_VISIBLE_COUNT),
    },
  };
};

export const DeckRoot = ({
  "aria-label": ariaLabel,
  "aria-labelledby": ariaLabelledBy,
  children,
  className,
  index,
  onExhausted,
  onIndexChange,
  onKeyDown,
  onAdvance,
  onAdvanceEnd,
  ref,
  renderOverlay,
  style,
  tabIndex,
  ...rest
}: DeckRootProps) => {
  const {
    props,
    tuning: {
      allowedDirections,
      defaultIndex,
      disabled,
      distanceThreshold,
      dragElastic,
      enter,
      mode,
      peekOffset,
      perspective,
      rotation,
      scaleStep,
      velocityThreshold,
      visibleCount,
    },
  } = splitDeckTuning(rest);
  const generatedId = useId();
  const [state, dispatch] = useReducer(deckReducer, defaultIndex, createDeckState);
  const reduceMotion = useReducedMotion() === true;
  const controlled = index !== undefined;
  const activeIndex = controlled ? index : state.internalIndex;
  const { cards, empty } = useDeckChildren(children, generatedId);
  const visibleCards = getVisibleDeckItems(cards, activeIndex, visibleCount, mode);
  const [activeCard] = visibleCards;
  const enteringIds = useEnteringCardIds(visibleCards, enter);
  const exhausted = mode === "finite" && visibleCards.length === 0;

  const isDragging = state.dragOffset !== 0;
  const dragProgress = Math.min(1, Math.abs(state.dragOffset) / BG_RESPONSE_RAMP);

  const exitCustom = { direction: state.lastDirection, velocity: state.exitVelocity };
  const interactions = useDeckInteractions({
    activeCard,
    activeIndex,
    allowedDirections,
    cards,
    controlled,
    disabled,
    dispatch,
    distanceThreshold,
    mode,
    onAdvance,
    onAdvanceEnd,
    onExhausted,
    onIndexChange,
    onKeyDown,
    velocityThreshold,
  });

  const rootStyle = { ...style, "--deck-perspective": `${perspective}px` } as CSSProperties;
  const controlProps = getDeckControlProps({
    activeIndex,
    ariaLabel,
    ariaLabelledBy,
    itemId: activeCard?.id,
    total: cards.length,
  });
  const rootDataProps = getDeckRootDataProps(disabled, exhausted);

  return (
    <div
      {...props}
      {...rootDataProps}
      className={joinClassNames("patternmode-deck", className)}
      ref={ref}
      style={rootStyle}
      tabIndex={tabIndex}
    >
      <input
        {...controlProps}
        className="patternmode-deck__control"
        disabled={disabled}
        onKeyDown={interactions.handleKeyDown}
      />
      <DeckRenderedCards
        activeIndex={activeIndex}
        cardsLength={cards.length}
        disabled={disabled}
        dragElastic={dragElastic}
        dragOffset={state.dragOffset}
        dragProgress={dragProgress}
        enteringIds={enteringIds}
        exitCustom={exitCustom}
        interactions={interactions}
        isDragging={isDragging}
        lastDirection={state.lastDirection}
        mode={mode}
        peekOffset={peekOffset}
        reduceMotion={reduceMotion}
        renderOverlay={renderOverlay}
        rotation={rotation}
        scaleStep={scaleStep}
        visibleCards={visibleCards}
        visualBaseIndex={state.visualBaseIndex}
      />
      {exhausted && empty !== null ? empty : null}
    </div>
  );
};

DeckRoot.displayName = "Deck";

const Deck = Object.assign(DeckRoot, {
  Card: DeckCard,
  Empty: DeckEmpty,
});

const CardStack = Deck;

export { CardStack, Deck };
