// vendored from @patternmode/deck@0.3.5 — generated by scripts/build-registry.mjs; do not hand-edit.
import type { AdvanceDirection } from "../types";
import { CARD_EXIT_FAST_SPRING, CARD_EXIT_SLOW_SPRING, EXIT_ROTATION } from "./deck-constants";

export const cardExitVariants = {
  exit: (custom: { velocity: number; direction: AdvanceDirection | null }) => {
    const speed = Math.abs(custom?.velocity ?? 0);
    const dir = custom?.direction;
    return {
      opacity: 0,
      rotate: dir === "left" ? -EXIT_ROTATION : EXIT_ROTATION,
      scale: 0.96,
      transition: {
        ...(speed > 600 ? CARD_EXIT_FAST_SPRING : CARD_EXIT_SLOW_SPRING),
        opacity: { duration: 0.15, ease: "easeIn" as const },
      },
      x: dir === "left" ? "-120%" : "120%",
    };
  },
};
