"use client";

export {
  DistributionBar,
  type DistributionBarProps,
  type DistributionBarSegment,
  type DistributionBarSegmentUpdate,
  DistributionDisplay,
  type DistributionDisplayProps,
  getDistributionBoundaryPercent,
  getDistributionTotal,
  getSwatchAtmosphereBackground,
  getSwatchColorsBackground,
  getSwatchSizeVariableStyle,
  moveDistributionBoundary,
  removeDistributionSegment,
  SWATCH_SHAPES,
  SWATCH_SIZE_VALUES,
  SWATCH_SIZES,
  SWATCH_TEXTURES,
  Swatch,
  type SwatchAsChildProps,
  type SwatchAtmosphereOptions,
  type SwatchColorStop,
  type SwatchDefaultProps,
  type SwatchProps,
  type SwatchShape,
  type SwatchSharedProps,
  type SwatchSize,
  type SwatchTexture,
  updateDistributionSegment,
} from "./swatch";
