"use client";
// vendored from @patternmode/tags@2.0.0 — generated by scripts/build-registry.mjs; do not hand-edit.

export { Badge, Tag, TagSelector } from "./tags";
export type {
  BadgeProps,
  BadgeVariant,
  TagItem,
  TagOptionRenderProps,
  TagProps,
  TagRenderProps,
  TagSelectorContentProps,
  TagSelectorEmptyProps,
  TagSelectorListProps,
  TagSelectorProps,
  TagSelectorRootProps,
  TagSelectorSearchProps,
  TagSelectorTriggerProps,
  TagSize,
  TagTone,
} from "./types";
