// vendored from @patternmode/tags@2.0.1 — generated by scripts/build-registry.mjs; do not hand-edit.
import { mergeProps } from "@base-ui/react/merge-props";
import { useRender } from "@base-ui/react/use-render";

export { mergeProps, useRender };

/**
 * Public `render` prop type. Pass a React element (`render={<a href="…" />}`)
 * to render the component's styling and behaviour through that element instead
 * of its default tag, or a function for full control over prop spreading.
 */
export type RenderProp<State = Record<string, unknown>> = useRender.RenderProp<State>;
