"use client";
// vendored from @patternmode/tags@1.1.1 — generated by scripts/build-registry.mjs; do not hand-edit.

import { createContext, use } from "react";
import type { ReactNode } from "react";

import type { TagItem, TagOptionRenderProps, TagRenderProps } from "./types";

export type CommandOption =
  | {
      id: string;
      label: string;
      type: "create";
      value: string;
    }
  | {
      id: string;
      item: TagItem;
      label: string;
      type: "item";
    };

export interface TagSelectorContextValue {
  activeIndex: number;
  activeOption: CommandOption | undefined;
  ariaLabel: string | undefined;
  commandOptions: CommandOption[];
  disabled: boolean;
  emptyMessage: ReactNode;
  filteredOptions: TagItem[];
  inputId: string;
  listboxId: string;
  name: string | undefined;
  onSearchInput: (query: string) => void;
  open: boolean;
  placeholder: string;
  query: string;
  removeItem: (item: TagItem) => void;
  renderOption: ((props: TagOptionRenderProps) => ReactNode) | undefined;
  renderTag: ((props: TagRenderProps) => ReactNode) | undefined;
  resolveDraft: (draft: string) => Promise<void>;
  resolveDrafts: (drafts: readonly string[]) => Promise<void>;
  selectCommandOption: (option: CommandOption) => Promise<void>;
  serializeItem: (item: TagItem) => string;
  separators: readonly string[];
  setActiveIndex: (index: number | ((currentIndex: number) => number)) => void;
  setOpen: (open: boolean) => void;
  value: readonly TagItem[];
}

export const TagSelectorContext = createContext<TagSelectorContextValue | null>(null);

export const useTagSelectorContext = (): TagSelectorContextValue => {
  const context = use(TagSelectorContext);
  if (context === null) {
    throw new Error("TagSelector parts must be rendered inside <TagSelector.Root>.");
  }

  return context;
};
