// vendored from @patternmode/tags@2.0.1 — generated by scripts/build-registry.mjs; do not hand-edit.
import type { TagItem } from "./types";

export const DEFAULT_SEPARATORS = ["Enter", ","] as const;
export const NO_ACTIVE_OPTION = -1;

export const normalizeTag = (value: string): string => value.trim().replaceAll(/\s+/gu, " ");

export const normalizeComparable = (value: string): string =>
  normalizeTag(value).toLocaleLowerCase();

export const splitPastedTags = (value: string): string[] =>
  value.split(/[,\n\r\t]+/u).flatMap((part) => {
    const tag = normalizeTag(part);
    return tag === "" ? [] : [tag];
  });

/** Drops empty drafts and drafts whose normalized comparable label already appeared. */
export const dedupeDrafts = (drafts: readonly string[]): string[] => {
  const seen = new Set<string>();

  return drafts.filter((draft) => {
    const comparableDraft = normalizeComparable(draft);
    if (comparableDraft === "" || seen.has(comparableDraft)) {
      return false;
    }
    seen.add(comparableDraft);
    return true;
  });
};

/** True when a key commits the current search draft (Enter or a configured separator). */
export const isCommitKey = (key: string, separators: readonly string[]): boolean =>
  key === "Enter" || separators.includes(key);

export const defaultFilterOption = (item: TagItem, query: string): boolean =>
  item.label.toLocaleLowerCase().includes(query.toLocaleLowerCase());

export const getNextIndex = (currentIndex: number, length: number): number => {
  if (length === 0) {
    return NO_ACTIVE_OPTION;
  }

  return currentIndex < 0 ? 0 : (currentIndex + 1) % length;
};

export const getPreviousIndex = (currentIndex: number, length: number): number => {
  if (length === 0) {
    return NO_ACTIVE_OPTION;
  }

  return currentIndex <= 0 ? length - 1 : currentIndex - 1;
};
