"use client";
// vendored from @patternmode/tags@2.0.2 — generated by scripts/build-registry.mjs; do not hand-edit.

import { Popover } from "@base-ui/react/popover";
import { ScrollFrame } from "@/components/patternmode/scrollframe";
import { joinClassNames } from "@/lib/patternmode/system";
import { useEffect, useRef } from "react";
import type { ClipboardEvent, KeyboardEvent, MouseEvent, ReactElement, ReactNode } from "react";

import { useRender } from "./render";
import { useTagSelectorContext } from "./tag-selector-context";
import type { CommandOption, TagSelectorContextValue } from "./tag-selector-context";
import { TagSelectorRoot } from "./tag-selector-root";
import { getNextIndex, getPreviousIndex, isCommitKey, splitPastedTags } from "./tag-selector-utils";
import type {
  BadgeProps,
  BadgeVariant,
  TagItem,
  TagOptionRenderProps,
  TagProps,
  TagSelectorContentProps,
  TagSelectorEmptyProps,
  TagSelectorListProps,
  TagSelectorProps,
  TagSelectorSearchProps,
  TagSelectorTriggerProps,
  TagTone,
} from "./types";

const DEFAULT_BADGE_VARIANT = "default" satisfies BadgeVariant;
const LEGACY_TONE_PROP = "tone" as const;
const TONE_VARIANT_MAP = {
  accent: "default",
  danger: "destructive",
  info: "secondary",
  neutral: "secondary",
  success: "secondary",
  warning: "outline",
} as const satisfies Record<TagTone, BadgeVariant>;

const getTagVariant = (variant: BadgeVariant | undefined, tone?: TagTone) =>
  variant ?? (tone === undefined ? "secondary" : TONE_VARIANT_MAP[tone]);

export const Badge = (props: BadgeProps): ReactElement => {
  const { render, className, variant = DEFAULT_BADGE_VARIANT, ...badgeProps } = props;

  return useRender({
    defaultTagName: "span",
    props: {
      // Defaults first so consumer props (e.g. Tag's `data-slot="tag"`) win,
      // matching the previous `{...badgeProps}`-last spread order.
      "data-slot": "badge",
      "data-variant": variant,
      ...badgeProps,
      className: joinClassNames("patternmode-badge", className),
    },
    render,
  });
};

export const Tag = (props: TagProps): ReactElement => {
  const {
    children,
    className,
    disabled = false,
    icon: Icon,
    onRemove,
    removeLabel,
    selected = false,
    size = "base",
    variant,
    [LEGACY_TONE_PROP]: legacyTone,
    ...tagProps
  } = props;

  const handleRemove = (event: MouseEvent<HTMLButtonElement>) => {
    event.stopPropagation();
    onRemove?.();
  };

  return (
    <Badge
      {...tagProps}
      className={joinClassNames("patternmode-tag", className)}
      data-disabled={disabled ? "true" : undefined}
      data-selected={selected ? "true" : undefined}
      data-size={size}
      data-slot="tag"
      data-testid="patternmode-tag"
      variant={getTagVariant(variant, legacyTone)}
    >
      {Icon === undefined ? null : (
        <span aria-hidden="true" className="patternmode-tag__icon">
          <Icon focusable="false" />
        </span>
      )}
      <span className="patternmode-tag__label">{children}</span>
      {onRemove === undefined ? null : (
        <button
          aria-label={removeLabel ?? "Remove tag"}
          className="patternmode-tag__remove"
          disabled={disabled}
          onClick={handleRemove}
          type="button"
        >
          <svg aria-hidden="true" fill="none" viewBox="0 0 20 20">
            <path d="M5.5 5.5l9 9M14.5 5.5l-9 9" />
          </svg>
        </button>
      )}
    </Badge>
  );
};

const TagSelectorTrigger = ({
  className,
  onClick,
  onKeyDown,
  placeholder,
  ref,
  tabIndex,
  ...triggerProps
}: TagSelectorTriggerProps) => {
  const context = useTagSelectorContext();
  const label = context.ariaLabel;

  const handleTriggerClick = (event: MouseEvent<HTMLButtonElement>) => {
    onClick?.(event);
    if (context.disabled) {
      event.preventDefault();
      event.stopPropagation();
    }
  };

  const handleKeyDown = (event: KeyboardEvent<HTMLButtonElement>) => {
    onKeyDown?.(event);
    if (event.defaultPrevented || context.disabled) {
      return;
    }

    if (event.key === "Enter" || event.key === " ") {
      event.preventDefault();
      context.setOpen(!context.open);
    }
  };

  return (
    <Popover.Trigger
      render={
        <button
          {...triggerProps}
          aria-controls={context.open ? context.listboxId : undefined}
          aria-disabled={context.disabled}
          aria-expanded={context.open}
          aria-haspopup="listbox"
          aria-label={label}
          className={joinClassNames("patternmode-tag-selector__trigger", className)}
          onClick={handleTriggerClick}
          onKeyDown={handleKeyDown}
          data-slot="tag-selector-trigger"
          ref={ref}
          tabIndex={context.disabled ? undefined : (tabIndex ?? 0)}
          type="button"
        />
      }
    >
      <ScrollFrame
        axes="horizontal"
        className="patternmode-tag-selector__scroll"
        contentClassName="patternmode-tag-selector__scroll-content"
        controls={false}
        data-testid="tag-selector-selected-scroll"
        fades="end"
        scrollbars="hidden"
      >
        {context.value.length > 0 ? (
          context.value.map((item) => {
            const removeProps = {
              "aria-label": `Remove ${item.label}`,
              disabled: context.disabled,
              onClick: (event: MouseEvent<HTMLButtonElement>) => {
                event.preventDefault();
                event.stopPropagation();
                if (!context.disabled) {
                  context.removeItem(item);
                }
              },
              type: "button" as const,
            };

            return (
              <span className="patternmode-tag-selector__selected-item" key={item.id}>
                {context.renderTag ? (
                  context.renderTag({
                    disabled: context.disabled,
                    item,
                    removeProps,
                    selected: true,
                  })
                ) : (
                  <Tag disabled={context.disabled} size="sm" variant={item.variant}>
                    {item.label}
                  </Tag>
                )}
              </span>
            );
          })
        ) : (
          <span className="patternmode-tag-selector__placeholder">
            {placeholder ?? context.placeholder}
          </span>
        )}
      </ScrollFrame>
    </Popover.Trigger>
  );
};

const TagSelectorContent = ({
  align = "start",
  className,
  ref,
  sideOffset = 6,
  ...contentProps
}: TagSelectorContentProps) => (
  <Popover.Portal>
    <Popover.Positioner align={align} sideOffset={sideOffset}>
      <Popover.Popup
        {...contentProps}
        className={joinClassNames("patternmode-tag-selector__content", className)}
        data-slot="tag-selector-content"
        ref={ref}
        // Base UI's Popup defaults to role="dialog"; passing role={undefined}
        // strips it (Base UI's prop merge honours the explicit undefined) so the
        // hand-built combobox/listbox pattern inside isn't wrapped in a dialog.
        // oxlint-disable-next-line jsx-a11y/aria-role, react-doctor/aria-role -- role is intentionally removed, not set to an invalid value.
        role={undefined}
      />
    </Popover.Positioner>
  </Popover.Portal>
);

const TagSelectorSearch = ({
  "aria-label": ariaLabel,
  className,
  onKeyDown,
  onPaste,
  ref,
  ...searchProps
}: TagSelectorSearchProps) => {
  const context = useTagSelectorContext();
  const localRef = useRef<HTMLInputElement | null>(null);
  const searchLabel =
    ariaLabel ??
    (context.ariaLabel !== undefined && context.ariaLabel !== ""
      ? `Search ${context.ariaLabel}`
      : "Search tags");

  useEffect(() => {
    if (context.open) {
      localRef.current?.focus();
    }
  }, [context.open]);

  const setRefs = (node: HTMLInputElement | null) => {
    localRef.current = node;
    if (typeof ref === "function") {
      ref(node);
    } else if (ref !== undefined && ref !== null) {
      ref.current = node;
    }
  };

  const handleKeyDownAsync = async (event: KeyboardEvent<HTMLInputElement>): Promise<void> => {
    onKeyDown?.(event);
    if (event.defaultPrevented) {
      return;
    }

    if (event.key === "ArrowDown") {
      event.preventDefault();
      context.setActiveIndex((currentIndex) =>
        getNextIndex(currentIndex, context.commandOptions.length),
      );
      return;
    }

    if (event.key === "ArrowUp") {
      event.preventDefault();
      context.setActiveIndex((currentIndex) =>
        getPreviousIndex(currentIndex, context.commandOptions.length),
      );
      return;
    }

    if (event.nativeEvent.isComposing && isCommitKey(event.key, context.separators)) {
      return;
    }

    if (event.key === "Enter" && context.activeOption !== undefined) {
      event.preventDefault();
      await context.selectCommandOption(context.activeOption);
      return;
    }

    if (isCommitKey(event.key, context.separators)) {
      event.preventDefault();
      await context.resolveDraft(context.query);
      return;
    }

    if (event.key === "Backspace" && context.query === "" && context.value.length > 0) {
      event.preventDefault();
      const lastItem = context.value.at(-1);
      if (lastItem !== undefined) {
        context.removeItem(lastItem);
      }
    }
  };

  const handlePasteAsync = async (event: ClipboardEvent<HTMLInputElement>): Promise<void> => {
    onPaste?.(event);
    if (event.defaultPrevented) {
      return;
    }

    const pastedTags = splitPastedTags(event.clipboardData.getData("text"));
    if (pastedTags.length <= 1) {
      return;
    }

    event.preventDefault();
    await context.resolveDrafts(pastedTags);
  };

  const handleKeyDown = (event: KeyboardEvent<HTMLInputElement>) => {
    void handleKeyDownAsync(event);
  };

  const handlePaste = (event: ClipboardEvent<HTMLInputElement>) => {
    void handlePasteAsync(event);
  };

  return (
    <input
      {...searchProps}
      aria-activedescendant={context.activeOption?.id}
      aria-autocomplete="list"
      aria-controls={context.listboxId}
      // eslint-disable-next-line jsx-a11y/role-supports-aria-props, react-doctor/role-supports-aria-props -- the explicit combobox role below makes aria-expanded valid.
      aria-expanded={context.open}
      aria-label={searchLabel}
      className={joinClassNames("patternmode-tag-selector__search", className)}
      disabled={context.disabled}
      id={context.inputId}
      onChange={(event) => {
        context.onSearchInput(event.target.value);
      }}
      onKeyDown={handleKeyDown}
      onPaste={handlePaste}
      ref={setRefs}
      // eslint-disable-next-line react-doctor/no-redundant-roles -- a bare text input is a textbox, not a combobox; the role is required for listbox popup semantics.
      role="combobox"
      type="text"
      value={context.query}
    />
  );
};

const TagSelectorRenderedOption = ({
  active,
  disabled,
  item,
  optionProps,
  renderOption: render,
  selected,
}: {
  active: boolean;
  disabled: boolean;
  item: TagItem;
  optionProps: TagOptionRenderProps["optionProps"];
  renderOption: NonNullable<TagSelectorContextValue["renderOption"]>;
  selected: boolean;
}) => (
  <>
    {render({
      active,
      disabled,
      item,
      optionProps,
      selected,
    })}
  </>
);

const TagSelectorOption = ({ item, option }: { item?: TagItem; option?: CommandOption }) => {
  const context = useTagSelectorContext();
  const resolvedOption =
    option ??
    (item === undefined
      ? undefined
      : {
          id: `${context.listboxId}-option-${item.id}`,
          item,
          label: item.label,
          type: "item" as const,
        });

  if (resolvedOption === undefined) {
    return null;
  }

  const isCreate = resolvedOption.type === "create";
  const optionItem = isCreate ? undefined : resolvedOption.item;
  const selected =
    optionItem === undefined
      ? false
      : context.value.some((selectedItem) => selectedItem.id === optionItem.id);
  const disabled = context.disabled || (selected ? false : optionItem?.disabled === true);
  const active = context.commandOptions[context.activeIndex]?.id === resolvedOption.id;
  const optionProps = {
    "aria-selected": selected,
    className: "patternmode-tag-selector__option",
    "data-active": active ? "true" : undefined,
    "data-slot": "tag-selector-option",
    disabled,
    id: resolvedOption.id,
    onClick: () => {
      void context.selectCommandOption(resolvedOption);
    },
    role: "option",
  };
  let optionIcon: ReactNode = null;

  if (isCreate) {
    optionIcon = (
      <svg aria-hidden="true" fill="none" viewBox="0 0 20 20">
        <path d="M10 4.5v11M4.5 10h11" />
      </svg>
    );
  } else if (selected) {
    optionIcon = (
      <svg aria-hidden="true" fill="none" viewBox="0 0 20 20">
        <path d="M4.5 10.5l3.25 3.25 7.75-8" />
      </svg>
    );
  }

  if (optionItem !== undefined && context.renderOption !== undefined) {
    return (
      <TagSelectorRenderedOption
        active={active}
        disabled={disabled}
        item={optionItem}
        optionProps={optionProps}
        renderOption={context.renderOption}
        selected={selected}
      />
    );
  }

  return (
    <button type="button" {...optionProps}>
      <span aria-hidden="true" className="patternmode-tag-selector__option-icon">
        {optionIcon}
      </span>
      <span className="patternmode-tag-selector__option-label">{resolvedOption.label}</span>
    </button>
  );
};

const TagSelectorEmpty = ({ className, ref, ...emptyProps }: TagSelectorEmptyProps) => (
  <div
    {...emptyProps}
    className={joinClassNames("patternmode-tag-selector__empty", className)}
    data-slot="tag-selector-empty"
    ref={ref}
  />
);

const TagSelectorList = ({ children, className, ref, ...listProps }: TagSelectorListProps) => {
  const context = useTagSelectorContext();
  const activeOptionId = context.activeOption?.id;

  useEffect(() => {
    if (activeOptionId === undefined) {
      return;
    }
    // eslint-disable-next-line unicorn/prefer-query-selector -- ids from useId contain ":" which is invalid inside a CSS selector.
    document.getElementById(activeOptionId)?.scrollIntoView({ block: "nearest" });
  }, [activeOptionId]);

  const generatedChildren =
    context.commandOptions.length > 0 ? (
      context.commandOptions.map((option) => <TagSelectorOption key={option.id} option={option} />)
    ) : (
      <TagSelectorEmpty>{context.emptyMessage}</TagSelectorEmpty>
    );

  return (
    <div
      {...listProps}
      className={joinClassNames("patternmode-tag-selector__list", className)}
      data-slot="tag-selector-list"
      id={context.listboxId}
      ref={ref}
      // eslint-disable-next-line jsx-a11y/prefer-tag-over-role, react-doctor/prefer-tag-over-role -- datalist/select cannot host interactive custom option buttons; this is a composite combobox listbox.
      role="listbox"
    >
      {children ?? generatedChildren}
    </div>
  );
};

const TagSelectorBase = (props: TagSelectorProps): ReactElement => {
  const {
    children,
    contentClassName,
    emptyMessage = "No tags found.",
    placeholder = "Select tags",
    searchPlaceholder,
    triggerClassName,
    ...rootProps
  } = props;

  return (
    <TagSelectorRoot {...rootProps} emptyMessage={emptyMessage} placeholder={placeholder}>
      {children ?? (
        <>
          <TagSelectorTrigger className={triggerClassName} placeholder={placeholder} />
          <TagSelectorContent className={contentClassName}>
            <TagSelectorSearch placeholder={searchPlaceholder} />
            <TagSelectorList />
          </TagSelectorContent>
        </>
      )}
    </TagSelectorRoot>
  );
};

const TagSelector = Object.assign(TagSelectorBase, {
  Content: TagSelectorContent,
  Empty: TagSelectorEmpty,
  List: TagSelectorList,
  Option: TagSelectorOption,
  Root: TagSelectorRoot,
  Search: TagSelectorSearch,
  Trigger: TagSelectorTrigger,
});

export { TagSelector };
