// vendored from @patternmode/stacksheet@2.0.0 — generated by scripts/build-registry.mjs; do not hand-edit.
import type { StoreApi } from "zustand";

import type { SheetActions, SheetContentComponent, StacksheetSnapshot } from "../types";

export type AnyComponent = SheetContentComponent<Record<string, unknown>>;

export type StoreState<TMap extends object> = StacksheetSnapshot<TMap> & SheetActions<TMap>;

/** Return type of createSheetStore — store plus ad-hoc component maps */
export interface SheetStoreBundle<TMap extends object> {
  /** Generated type key → Component (for renderer lookup) */
  componentMap: Map<string, AnyComponent>;
  /** Component → generated type key (dedup) */
  componentRegistry: Map<AnyComponent, string>;
  store: StoreApi<StoreState<TMap>>;
}

/** Pre-resolved args — skips resolveArgs entirely */
export interface ResolvedItem {
  ariaLabel?: string;
  data: Record<string, unknown>;
  id: string;
  type: string;
}
