// vendored from @patternmode/stacksheet@2.0.2 — generated by scripts/build-registry.mjs; do not hand-edit.
import type { SheetPresentationOptions } from "../types";
import type { AnyComponent, ResolvedItem } from "./store-types";

const isRecord = (value: unknown): value is Record<string, unknown> =>
  typeof value === "object" && value !== null;

export const toRecord = (value: unknown): Record<string, unknown> => (isRecord(value) ? value : {});

export const isComponent = (value: unknown): value is AnyComponent => typeof value === "function";

const getComponentName = (component: AnyComponent): string | undefined => {
  const name = component.displayName ?? component.name;
  return name === "" ? undefined : name;
};

const getNodeEnv = (): string | undefined => globalThis.process?.env?.NODE_ENV;

/**
 * Generate a unique sheet id. `crypto.randomUUID` is only available in
 * secure contexts, so fall back to a timestamp + random suffix on
 * non-secure origins (e.g. plain-HTTP LAN dev servers).
 */
export const generateSheetId = (): string => {
  if (typeof globalThis.crypto?.randomUUID === "function") {
    return globalThis.crypto.randomUUID();
  }
  return `sheet-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 10)}`;
};

export const getStringArg = (value: unknown, name: string): string => {
  if (typeof value !== "string") {
    throw new TypeError(`Expected ${name} to be a string.`);
  }
  return value;
};

export const resolvePresentationOptions = (
  value: unknown,
): SheetPresentationOptions | undefined => {
  if (!isRecord(value)) {
    return undefined;
  }
  const { ariaLabel } = value;
  if (ariaLabel !== undefined && typeof ariaLabel !== "string") {
    return undefined;
  }
  return ariaLabel === undefined ? {} : { ariaLabel };
};
/**
 * Dev-mode warning: detect likely inline arrow functions passed as ad-hoc components.
 * When a new component reference has the same displayName/name as an existing one,
 * it's almost always an inline arrow being re-created every render.
 */
export const warnInlineComponent = (
  component: AnyComponent,
  componentRegistry: Map<AnyComponent, string>,
  warnedNames: Set<string>,
): void => {
  if (getNodeEnv() === "production") {
    return;
  }
  const name = getComponentName(component);
  if (name === undefined) {
    return;
  }
  if (warnedNames.has(name)) {
    return;
  }
  for (const [existing, key] of componentRegistry) {
    const existingName = getComponentName(existing);
    if (existingName === name) {
      warnedNames.add(name);
      console.warn(
        `[stacksheet] A new component reference with name "${name}" was registered ` +
          `(key: ${key}), but a different reference with the same name already exists. ` +
          `This usually means you're passing an inline arrow function (e.g. ` +
          "open(() => <MySheet />)). Define the component outside of render to avoid " +
          "memory leaks and broken navigate() same-type detection.",
      );
      return;
    }
  }
};

export const registerComponent = (
  component: AnyComponent,
  componentRegistry: Map<AnyComponent, string>,
  componentMap: Map<string, AnyComponent>,
  getNextKey: () => string,
  warnedNames: Set<string>,
): string => {
  const existingKey = componentRegistry.get(component);
  if (existingKey !== undefined) {
    return existingKey;
  }

  warnInlineComponent(component, componentRegistry, warnedNames);
  const nextKey = getNextKey();
  componentRegistry.set(component, nextKey);
  componentMap.set(nextKey, component);
  return nextKey;
};
/**
 * If `first` is a function (component), register it and return { type, id, data }.
 * Otherwise, pass through the string-based (type, id, data) args unchanged.
 */
export const resolveArgs = (
  componentRegistry: Map<AnyComponent, string>,
  componentMap: Map<string, AnyComponent>,
  getNextKey: () => string,
  warnedNames: Set<string>,
  first: unknown,
  second: unknown,
  third: unknown,
  fourth?: unknown,
): ResolvedItem => {
  if (isComponent(first)) {
    const typeKey = registerComponent(
      first,
      componentRegistry,
      componentMap,
      getNextKey,
      warnedNames,
    );
    if (typeof second === "string") {
      return {
        ariaLabel: resolvePresentationOptions(fourth)?.ariaLabel,
        data: toRecord(third),
        id: second,
        type: typeKey,
      };
    }
    return {
      ariaLabel: resolvePresentationOptions(third)?.ariaLabel,
      data: toRecord(second),
      id: generateSheetId(),
      type: typeKey,
    };
  }
  return {
    ariaLabel: resolvePresentationOptions(fourth)?.ariaLabel,
    data: toRecord(third),
    id: getStringArg(second, "sheet id"),
    type: getStringArg(first, "sheet type"),
  };
};
