// vendored from @howells/motion@0.1.0 — generated by scripts/build-registry.mjs; do not hand-edit.
export const durations = {
  instant: 0,
  moderate: 0.4,
  normal: 0.25,
  quick: 0.12,
  slow: 1,
  snappy: 0.22,
} as const;

export type Duration = keyof typeof durations;

const toMs = (seconds: number): number => Math.round(seconds * 1000);

/** Duration tokens in milliseconds for CSS/Tailwind usage. Derived from `durations`. */
export const durationMs: Record<Duration, number> = {
  instant: toMs(durations.instant),
  moderate: toMs(durations.moderate),
  normal: toMs(durations.normal),
  quick: toMs(durations.quick),
  slow: toMs(durations.slow),
  snappy: toMs(durations.snappy),
};
