// vendored from @howells/motion@0.1.0 — generated by scripts/build-registry.mjs; do not hand-edit.
export { durationMs, durations } from "./durations";
export type { Duration } from "./durations";
export { easings, easingsCSS } from "./easings";
export type { Easing, EasingTuple } from "./easings";
export { presets, shakeKeyframes } from "./presets";
export type { Preset } from "./presets";
export { prefersReducedMotion } from "./reduced-motion";
export { scales } from "./scales";
export type { Scale } from "./scales";
export { springs } from "./springs";
export type { SpringType } from "./springs";
