// vendored from @howells/motion@0.2.0 — generated by scripts/build-registry.mjs; do not hand-edit.
import { durations } from "./durations";
import { easings } from "./easings";
import { springs } from "./springs";

/**
 * Semantic transition presets combining durations, easings, and springs.
 *
 * Use these for common patterns to ensure consistency across the app.
 * Composition-based: spread these into your transition prop.
 *
 * @example
 * ```tsx
 * <motion.div transition={presets.dialogOpen} />
 * ```
 */
export const presets = {
  dialogClose: { duration: durations.quick, ease: easings.customIn },
  dialogOpen: { duration: durations.normal, ease: easings.customOut },
  fadeIn: { duration: durations.quick, ease: easings.customOut },
  fadeOut: { duration: durations.quick, ease: easings.customIn },
  hoverLift: springs.snappy,
  hoverSettle: springs.natural,
  shake: { duration: durations.normal, ease: easings.customOut },
  slideIn: { duration: durations.normal, ease: easings.customOut },
  slideOut: { duration: durations.quick, ease: easings.customIn },
  /** Crisp emergence — peeks, lifts, and small reveals on hover/focus */
  snappy: { duration: durations.snappy, ease: easings.snappy },
} as const;

/**
 * Shake animation keyframes for error feedback.
 * Apply to the `x` property with `animate` prop.
 *
 * @example
 * ```tsx
 * <motion.div
 *   animate={hasError ? { x: shakeKeyframes } : { x: 0 }}
 *   transition={presets.shake}
 * />
 * ```
 */
export const shakeKeyframes: readonly number[] = Object.freeze([0, -6, 6, -4, 4, 0]);

export type Preset = keyof typeof presets;
