// vendored from @howells/motion@0.2.0 — generated by scripts/build-registry.mjs; do not hand-edit.
export const prefersReducedMotion = (): boolean =>
  typeof window !== "undefined" &&
  typeof window.matchMedia === "function" &&
  window.matchMedia("(prefers-reduced-motion: reduce)").matches;
