// vendored from @howells/motion@0.1.0 — generated by scripts/build-registry.mjs; do not hand-edit.
export const scales = {
  hover: 1.02,
  hoverLift: 1.05,
  press: 0.97,
  pressDeep: 0.95,
} as const;

export type Scale = keyof typeof scales;
