// vendored from @howells/motion@0.2.0 — generated by scripts/build-registry.mjs; do not hand-edit.
export const springs = {
  bouncy: { damping: 12, mass: 1, stiffness: 260, type: "spring" },
  natural: { damping: 20, mass: 1, stiffness: 200, type: "spring" },
  playful: { damping: 15, mass: 1, stiffness: 170, type: "spring" },
  snappy: { damping: 28, mass: 0.8, stiffness: 400, type: "spring" },
  soft: { damping: 18, mass: 1, stiffness: 120, type: "spring" },
  stiff: { damping: 30, mass: 1, stiffness: 500, type: "spring" },
  subtle: { damping: 30, mass: 1, stiffness: 300, type: "spring" },
  swift: { damping: 30, mass: 0.5, stiffness: 500, type: "spring" },
} as const;

export type SpringType = keyof typeof springs;
